// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.6.1
// source: api/proto/v1/compilation-server.proto

package popcorn

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type RequiredStatus int32

const (
	RequiredStatus_DONE               RequiredStatus = 0
	RequiredStatus_SHA256_REQUIRED    RequiredStatus = 1
	RequiredStatus_FULL_COPY_REQUIRED RequiredStatus = 2
)

// Enum value maps for RequiredStatus.
var (
	RequiredStatus_name = map[int32]string{
		0: "DONE",
		1: "SHA256_REQUIRED",
		2: "FULL_COPY_REQUIRED",
	}
	RequiredStatus_value = map[string]int32{
		"DONE":               0,
		"SHA256_REQUIRED":    1,
		"FULL_COPY_REQUIRED": 2,
	}
)

func (x RequiredStatus) Enum() *RequiredStatus {
	p := new(RequiredStatus)
	*p = x
	return p
}

func (x RequiredStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RequiredStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_v1_compilation_server_proto_enumTypes[0].Descriptor()
}

func (RequiredStatus) Type() protoreflect.EnumType {
	return &file_api_proto_v1_compilation_server_proto_enumTypes[0]
}

func (x RequiredStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RequiredStatus.Descriptor instead.
func (RequiredStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_v1_compilation_server_proto_rawDescGZIP(), []int{0}
}

type SHA256Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	B0_7   uint64 `protobuf:"fixed64,1,opt,name=B0_7,json=B07,proto3" json:"B0_7,omitempty"`
	B8_15  uint64 `protobuf:"fixed64,2,opt,name=B8_15,json=B815,proto3" json:"B8_15,omitempty"`
	B16_23 uint64 `protobuf:"fixed64,3,opt,name=B16_23,json=B1623,proto3" json:"B16_23,omitempty"`
	B24_31 uint64 `protobuf:"fixed64,4,opt,name=B24_31,json=B2431,proto3" json:"B24_31,omitempty"`
}

func (x *SHA256Message) Reset() {
	*x = SHA256Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_v1_compilation_server_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SHA256Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SHA256Message) ProtoMessage() {}

func (x *SHA256Message) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_compilation_server_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SHA256Message.ProtoReflect.Descriptor instead.
func (*SHA256Message) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_compilation_server_proto_rawDescGZIP(), []int{0}
}

func (x *SHA256Message) GetB0_7() uint64 {
	if x != nil {
		return x.B0_7
	}
	return 0
}

func (x *SHA256Message) GetB8_15() uint64 {
	if x != nil {
		return x.B8_15
	}
	return 0
}

func (x *SHA256Message) GetB16_23() uint64 {
	if x != nil {
		return x.B16_23
	}
	return 0
}

func (x *SHA256Message) GetB24_31() uint64 {
	if x != nil {
		return x.B24_31
	}
	return 0
}

type FileMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FilePath string `protobuf:"bytes,1,opt,name=FilePath,proto3" json:"FilePath,omitempty"`
	MTime    int64  `protobuf:"varint,2,opt,name=MTime,proto3" json:"MTime,omitempty"`
	FileSize int64  `protobuf:"varint,3,opt,name=FileSize,proto3" json:"FileSize,omitempty"`
}

func (x *FileMetadata) Reset() {
	*x = FileMetadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_v1_compilation_server_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileMetadata) ProtoMessage() {}

func (x *FileMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_compilation_server_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileMetadata.ProtoReflect.Descriptor instead.
func (*FileMetadata) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_compilation_server_proto_rawDescGZIP(), []int{1}
}

func (x *FileMetadata) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *FileMetadata) GetMTime() int64 {
	if x != nil {
		return x.MTime
	}
	return 0
}

func (x *FileMetadata) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

type StartCompilationSessionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID          *SHA256Message  `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	UserName        string          `protobuf:"bytes,2,opt,name=UserName,proto3" json:"UserName,omitempty"`
	SourceFilePath  string          `protobuf:"bytes,3,opt,name=SourceFilePath,proto3" json:"SourceFilePath,omitempty"`
	Compiler        string          `protobuf:"bytes,4,opt,name=Compiler,proto3" json:"Compiler,omitempty"`
	CompilerArgs    []string        `protobuf:"bytes,5,rep,name=CompilerArgs,proto3" json:"CompilerArgs,omitempty"`
	RequiredHeaders []*FileMetadata `protobuf:"bytes,6,rep,name=RequiredHeaders,proto3" json:"RequiredHeaders,omitempty"`
	UseObjectCache  bool            `protobuf:"varint,7,opt,name=UseObjectCache,proto3" json:"UseObjectCache,omitempty"`
}

func (x *StartCompilationSessionRequest) Reset() {
	*x = StartCompilationSessionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_v1_compilation_server_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartCompilationSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartCompilationSessionRequest) ProtoMessage() {}

func (x *StartCompilationSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_compilation_server_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartCompilationSessionRequest.ProtoReflect.Descriptor instead.
func (*StartCompilationSessionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_compilation_server_proto_rawDescGZIP(), []int{2}
}

func (x *StartCompilationSessionRequest) GetUserID() *SHA256Message {
	if x != nil {
		return x.UserID
	}
	return nil
}

func (x *StartCompilationSessionRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *StartCompilationSessionRequest) GetSourceFilePath() string {
	if x != nil {
		return x.SourceFilePath
	}
	return ""
}

func (x *StartCompilationSessionRequest) GetCompiler() string {
	if x != nil {
		return x.Compiler
	}
	return ""
}

func (x *StartCompilationSessionRequest) GetCompilerArgs() []string {
	if x != nil {
		return x.CompilerArgs
	}
	return nil
}

func (x *StartCompilationSessionRequest) GetRequiredHeaders() []*FileMetadata {
	if x != nil {
		return x.RequiredHeaders
	}
	return nil
}

func (x *StartCompilationSessionRequest) GetUseObjectCache() bool {
	if x != nil {
		return x.UseObjectCache
	}
	return false
}

type RequiredFile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HeaderIndex int32          `protobuf:"varint,1,opt,name=HeaderIndex,proto3" json:"HeaderIndex,omitempty"`
	Status      RequiredStatus `protobuf:"varint,2,opt,name=Status,proto3,enum=popcorn.RequiredStatus" json:"Status,omitempty"`
}

func (x *RequiredFile) Reset() {
	*x = RequiredFile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_v1_compilation_server_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequiredFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequiredFile) ProtoMessage() {}

func (x *RequiredFile) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_compilation_server_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequiredFile.ProtoReflect.Descriptor instead.
func (*RequiredFile) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_compilation_server_proto_rawDescGZIP(), []int{3}
}

func (x *RequiredFile) GetHeaderIndex() int32 {
	if x != nil {
		return x.HeaderIndex
	}
	return 0
}

func (x *RequiredFile) GetStatus() RequiredStatus {
	if x != nil {
		return x.Status
	}
	return RequiredStatus_DONE
}

type StartCompilationSessionReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionID     uint64          `protobuf:"varint,1,opt,name=SessionID,proto3" json:"SessionID,omitempty"`
	RequiredFiles []*RequiredFile `protobuf:"bytes,2,rep,name=RequiredFiles,proto3" json:"RequiredFiles,omitempty"`
}

func (x *StartCompilationSessionReply) Reset() {
	*x = StartCompilationSessionReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_v1_compilation_server_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartCompilationSessionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartCompilationSessionReply) ProtoMessage() {}

func (x *StartCompilationSessionReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_compilation_server_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartCompilationSessionReply.ProtoReflect.Descriptor instead.
func (*StartCompilationSessionReply) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_compilation_server_proto_rawDescGZIP(), []int{4}
}

func (x *StartCompilationSessionReply) GetSessionID() uint64 {
	if x != nil {
		return x.SessionID
	}
	return 0
}

func (x *StartCompilationSessionReply) GetRequiredFiles() []*RequiredFile {
	if x != nil {
		return x.RequiredFiles
	}
	return nil
}

type TransferFileIn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Chunk:
	//	*TransferFileIn_Header
	//	*TransferFileIn_FileBodyChunk
	Chunk isTransferFileIn_Chunk `protobuf_oneof:"Chunk"`
}

func (x *TransferFileIn) Reset() {
	*x = TransferFileIn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_v1_compilation_server_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransferFileIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferFileIn) ProtoMessage() {}

func (x *TransferFileIn) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_compilation_server_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferFileIn.ProtoReflect.Descriptor instead.
func (*TransferFileIn) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_compilation_server_proto_rawDescGZIP(), []int{5}
}

func (m *TransferFileIn) GetChunk() isTransferFileIn_Chunk {
	if m != nil {
		return m.Chunk
	}
	return nil
}

func (x *TransferFileIn) GetHeader() *TransferFileIn_StreamHeader {
	if x, ok := x.GetChunk().(*TransferFileIn_Header); ok {
		return x.Header
	}
	return nil
}

func (x *TransferFileIn) GetFileBodyChunk() []byte {
	if x, ok := x.GetChunk().(*TransferFileIn_FileBodyChunk); ok {
		return x.FileBodyChunk
	}
	return nil
}

type isTransferFileIn_Chunk interface {
	isTransferFileIn_Chunk()
}

type TransferFileIn_Header struct {
	Header *TransferFileIn_StreamHeader `protobuf:"bytes,1,opt,name=Header,proto3,oneof"`
}

type TransferFileIn_FileBodyChunk struct {
	FileBodyChunk []byte `protobuf:"bytes,2,opt,name=FileBodyChunk,proto3,oneof"`
}

func (*TransferFileIn_Header) isTransferFileIn_Chunk() {}

func (*TransferFileIn_FileBodyChunk) isTransferFileIn_Chunk() {}

type TransferFileOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status RequiredStatus `protobuf:"varint,1,opt,name=status,proto3,enum=popcorn.RequiredStatus" json:"status,omitempty"`
}

func (x *TransferFileOut) Reset() {
	*x = TransferFileOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_v1_compilation_server_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransferFileOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferFileOut) ProtoMessage() {}

func (x *TransferFileOut) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_compilation_server_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferFileOut.ProtoReflect.Descriptor instead.
func (*TransferFileOut) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_compilation_server_proto_rawDescGZIP(), []int{6}
}

func (x *TransferFileOut) GetStatus() RequiredStatus {
	if x != nil {
		return x.Status
	}
	return RequiredStatus_DONE
}

type CompileSourceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionID              uint64 `protobuf:"varint,1,opt,name=SessionID,proto3" json:"SessionID,omitempty"`
	SourceBody             []byte `protobuf:"bytes,2,opt,name=SourceBody,proto3" json:"SourceBody,omitempty"`
	CloseSessionAfterBuild bool   `protobuf:"varint,3,opt,name=CloseSessionAfterBuild,proto3" json:"CloseSessionAfterBuild,omitempty"`
}

func (x *CompileSourceRequest) Reset() {
	*x = CompileSourceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_v1_compilation_server_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompileSourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompileSourceRequest) ProtoMessage() {}

func (x *CompileSourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_compilation_server_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompileSourceRequest.ProtoReflect.Descriptor instead.
func (*CompileSourceRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_compilation_server_proto_rawDescGZIP(), []int{7}
}

func (x *CompileSourceRequest) GetSessionID() uint64 {
	if x != nil {
		return x.SessionID
	}
	return 0
}

func (x *CompileSourceRequest) GetSourceBody() []byte {
	if x != nil {
		return x.SourceBody
	}
	return nil
}

func (x *CompileSourceRequest) GetCloseSessionAfterBuild() bool {
	if x != nil {
		return x.CloseSessionAfterBuild
	}
	return false
}

type CompileSourceReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CompilerRetCode int32  `protobuf:"varint,1,opt,name=CompilerRetCode,proto3" json:"CompilerRetCode,omitempty"`
	CompiledSource  []byte `protobuf:"bytes,2,opt,name=CompiledSource,proto3" json:"CompiledSource,omitempty"`
	CompilerStdout  []byte `protobuf:"bytes,3,opt,name=CompilerStdout,proto3" json:"CompilerStdout,omitempty"`
	CompilerStderr  []byte `protobuf:"bytes,4,opt,name=CompilerStderr,proto3" json:"CompilerStderr,omitempty"`
}

func (x *CompileSourceReply) Reset() {
	*x = CompileSourceReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_v1_compilation_server_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompileSourceReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompileSourceReply) ProtoMessage() {}

func (x *CompileSourceReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_compilation_server_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompileSourceReply.ProtoReflect.Descriptor instead.
func (*CompileSourceReply) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_compilation_server_proto_rawDescGZIP(), []int{8}
}

func (x *CompileSourceReply) GetCompilerRetCode() int32 {
	if x != nil {
		return x.CompilerRetCode
	}
	return 0
}

func (x *CompileSourceReply) GetCompiledSource() []byte {
	if x != nil {
		return x.CompiledSource
	}
	return nil
}

func (x *CompileSourceReply) GetCompilerStdout() []byte {
	if x != nil {
		return x.CompilerStdout
	}
	return nil
}

func (x *CompileSourceReply) GetCompilerStderr() []byte {
	if x != nil {
		return x.CompilerStderr
	}
	return nil
}

type CloseSessionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionID uint64 `protobuf:"varint,1,opt,name=SessionID,proto3" json:"SessionID,omitempty"`
}

func (x *CloseSessionRequest) Reset() {
	*x = CloseSessionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_v1_compilation_server_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CloseSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseSessionRequest) ProtoMessage() {}

func (x *CloseSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_compilation_server_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseSessionRequest.ProtoReflect.Descriptor instead.
func (*CloseSessionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_compilation_server_proto_rawDescGZIP(), []int{9}
}

func (x *CloseSessionRequest) GetSessionID() uint64 {
	if x != nil {
		return x.SessionID
	}
	return 0
}

type CloseSessionReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CloseSessionReply) Reset() {
	*x = CloseSessionReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_v1_compilation_server_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CloseSessionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseSessionReply) ProtoMessage() {}

func (x *CloseSessionReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_compilation_server_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseSessionReply.ProtoReflect.Descriptor instead.
func (*CloseSessionReply) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_compilation_server_proto_rawDescGZIP(), []int{10}
}

type StatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_v1_compilation_server_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_compilation_server_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_compilation_server_proto_rawDescGZIP(), []int{11}
}

type StatusReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerVersion string   `protobuf:"bytes,1,opt,name=ServerVersion,proto3" json:"ServerVersion,omitempty"`
	ServerArgs    []string `protobuf:"bytes,2,rep,name=ServerArgs,proto3" json:"ServerArgs,omitempty"`
	ServerStats   []byte   `protobuf:"bytes,3,opt,name=ServerStats,proto3" json:"ServerStats,omitempty"`
}

func (x *StatusReply) Reset() {
	*x = StatusReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_v1_compilation_server_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatusReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusReply) ProtoMessage() {}

func (x *StatusReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_compilation_server_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusReply.ProtoReflect.Descriptor instead.
func (*StatusReply) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_compilation_server_proto_rawDescGZIP(), []int{12}
}

func (x *StatusReply) GetServerVersion() string {
	if x != nil {
		return x.ServerVersion
	}
	return ""
}

func (x *StatusReply) GetServerArgs() []string {
	if x != nil {
		return x.ServerArgs
	}
	return nil
}

func (x *StatusReply) GetServerStats() []byte {
	if x != nil {
		return x.ServerStats
	}
	return nil
}

type TransferFileIn_StreamHeader struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionID  uint64         `protobuf:"varint,1,opt,name=SessionID,proto3" json:"SessionID,omitempty"`
	FileIndex  int32          `protobuf:"varint,2,opt,name=FileIndex,proto3" json:"FileIndex,omitempty"`
	FileSHA256 *SHA256Message `protobuf:"bytes,3,opt,name=FileSHA256,proto3" json:"FileSHA256,omitempty"`
}

func (x *TransferFileIn_StreamHeader) Reset() {
	*x = TransferFileIn_StreamHeader{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_v1_compilation_server_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransferFileIn_StreamHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferFileIn_StreamHeader) ProtoMessage() {}

func (x *TransferFileIn_StreamHeader) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_compilation_server_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferFileIn_StreamHeader.ProtoReflect.Descriptor instead.
func (*TransferFileIn_StreamHeader) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_compilation_server_proto_rawDescGZIP(), []int{5, 0}
}

func (x *TransferFileIn_StreamHeader) GetSessionID() uint64 {
	if x != nil {
		return x.SessionID
	}
	return 0
}

func (x *TransferFileIn_StreamHeader) GetFileIndex() int32 {
	if x != nil {
		return x.FileIndex
	}
	return 0
}

func (x *TransferFileIn_StreamHeader) GetFileSHA256() *SHA256Message {
	if x != nil {
		return x.FileSHA256
	}
	return nil
}

var File_api_proto_v1_compilation_server_proto protoreflect.FileDescriptor

var file_api_proto_v1_compilation_server_proto_rawDesc = []byte{
	0x0a, 0x25, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x31, 0x2f, 0x63,
	0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x70, 0x6f, 0x70, 0x63, 0x6f, 0x72, 0x6e,
	0x22, 0x65, 0x0a, 0x0d, 0x53, 0x48, 0x41, 0x32, 0x35, 0x36, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x11, 0x0a, 0x04, 0x42, 0x30, 0x5f, 0x37, 0x18, 0x01, 0x20, 0x01, 0x28, 0x06, 0x52,
	0x03, 0x42, 0x30, 0x37, 0x12, 0x13, 0x0a, 0x05, 0x42, 0x38, 0x5f, 0x31, 0x35, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x06, 0x52, 0x04, 0x42, 0x38, 0x31, 0x35, 0x12, 0x15, 0x0a, 0x06, 0x42, 0x31, 0x36,
	0x5f, 0x32, 0x33, 0x18, 0x03, 0x20, 0x01, 0x28, 0x06, 0x52, 0x05, 0x42, 0x31, 0x36, 0x32, 0x33,
	0x12, 0x15, 0x0a, 0x06, 0x42, 0x32, 0x34, 0x5f, 0x33, 0x31, 0x18, 0x04, 0x20, 0x01, 0x28, 0x06,
	0x52, 0x05, 0x42, 0x32, 0x34, 0x33, 0x31, 0x22, 0x5c, 0x0a, 0x0c, 0x46, 0x69, 0x6c, 0x65, 0x4d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x1a, 0x0a, 0x08, 0x46, 0x69, 0x6c, 0x65, 0x50,
	0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x46, 0x69, 0x6c, 0x65, 0x50,
	0x61, 0x74, 0x68, 0x12, 0x14, 0x0a, 0x05, 0x4d, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x05, 0x4d, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x46, 0x69, 0x6c,
	0x65, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x46, 0x69, 0x6c,
	0x65, 0x53, 0x69, 0x7a, 0x65, 0x22, 0xbd, 0x02, 0x0a, 0x1e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x43,
	0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2e, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x6f, 0x70, 0x63, 0x6f,
	0x72, 0x6e, 0x2e, 0x53, 0x48, 0x41, 0x32, 0x35, 0x36, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x55, 0x73, 0x65, 0x72,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x46, 0x69,
	0x6c, 0x65, 0x50, 0x61, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x53, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x50, 0x61, 0x74, 0x68, 0x12, 0x1a, 0x0a, 0x08,
	0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x65, 0x72, 0x12, 0x22, 0x0a, 0x0c, 0x43, 0x6f, 0x6d, 0x70,
	0x69, 0x6c, 0x65, 0x72, 0x41, 0x72, 0x67, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0c,
	0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x65, 0x72, 0x41, 0x72, 0x67, 0x73, 0x12, 0x3f, 0x0a, 0x0f,
	0x52, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x18,
	0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x6f, 0x70, 0x63, 0x6f, 0x72, 0x6e, 0x2e,
	0x46, 0x69, 0x6c, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x0f, 0x52, 0x65,
	0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x12, 0x26, 0x0a,
	0x0e, 0x55, 0x73, 0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x43, 0x61, 0x63, 0x68, 0x65, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0e, 0x55, 0x73, 0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x43, 0x61, 0x63, 0x68, 0x65, 0x22, 0x61, 0x0a, 0x0c, 0x52, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65,
	0x64, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x49,
	0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x48, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x2f, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x70, 0x6f, 0x70, 0x63, 0x6f, 0x72,
	0x6e, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x79, 0x0a, 0x1c, 0x53, 0x74, 0x61, 0x72,
	0x74, 0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x53, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x12, 0x3b, 0x0a, 0x0d, 0x52, 0x65, 0x71, 0x75, 0x69, 0x72,
	0x65, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e,
	0x70, 0x6f, 0x70, 0x63, 0x6f, 0x72, 0x6e, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64,
	0x46, 0x69, 0x6c, 0x65, 0x52, 0x0d, 0x52, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x46, 0x69,
	0x6c, 0x65, 0x73, 0x22, 0x86, 0x02, 0x0a, 0x0e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72,
	0x46, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x12, 0x3e, 0x0a, 0x06, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x70, 0x6f, 0x70, 0x63, 0x6f, 0x72, 0x6e,
	0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x2e,
	0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x48, 0x00, 0x52, 0x06,
	0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x26, 0x0a, 0x0d, 0x46, 0x69, 0x6c, 0x65, 0x42, 0x6f,
	0x64, 0x79, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52,
	0x0d, 0x46, 0x69, 0x6c, 0x65, 0x42, 0x6f, 0x64, 0x79, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x1a, 0x82,
	0x01, 0x0a, 0x0c, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12,
	0x1c, 0x0a, 0x09, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x09, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x12, 0x1c, 0x0a,
	0x09, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x09, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x36, 0x0a, 0x0a, 0x46,
	0x69, 0x6c, 0x65, 0x53, 0x48, 0x41, 0x32, 0x35, 0x36, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x16, 0x2e, 0x70, 0x6f, 0x70, 0x63, 0x6f, 0x72, 0x6e, 0x2e, 0x53, 0x48, 0x41, 0x32, 0x35, 0x36,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x0a, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x48, 0x41,
	0x32, 0x35, 0x36, 0x42, 0x07, 0x0a, 0x05, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x22, 0x42, 0x0a, 0x0f,
	0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x46, 0x69, 0x6c, 0x65, 0x4f, 0x75, 0x74, 0x12,
	0x2f, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x17, 0x2e, 0x70, 0x6f, 0x70, 0x63, 0x6f, 0x72, 0x6e, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x69, 0x72,
	0x65, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x22, 0x8c, 0x01, 0x0a, 0x14, 0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x65, 0x53, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x53, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x12, 0x1e, 0x0a, 0x0a, 0x53, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x42, 0x6f, 0x64, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x53, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x36, 0x0a, 0x16, 0x43, 0x6c, 0x6f, 0x73, 0x65,
	0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x41, 0x66, 0x74, 0x65, 0x72, 0x42, 0x75, 0x69, 0x6c,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x16, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x53, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x41, 0x66, 0x74, 0x65, 0x72, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x22,
	0xb6, 0x01, 0x0a, 0x12, 0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x65, 0x53, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x28, 0x0a, 0x0f, 0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c,
	0x65, 0x72, 0x52, 0x65, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0f, 0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x65, 0x72, 0x52, 0x65, 0x74, 0x43, 0x6f, 0x64, 0x65,
	0x12, 0x26, 0x0a, 0x0e, 0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x65, 0x64, 0x53, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0e, 0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c,
	0x65, 0x64, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x43, 0x6f, 0x6d, 0x70,
	0x69, 0x6c, 0x65, 0x72, 0x53, 0x74, 0x64, 0x6f, 0x75, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x0e, 0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x65, 0x72, 0x53, 0x74, 0x64, 0x6f, 0x75, 0x74,
	0x12, 0x26, 0x0a, 0x0e, 0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x65, 0x72, 0x53, 0x74, 0x64, 0x65,
	0x72, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0e, 0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c,
	0x65, 0x72, 0x53, 0x74, 0x64, 0x65, 0x72, 0x72, 0x22, 0x33, 0x0a, 0x13, 0x43, 0x6c, 0x6f, 0x73,
	0x65, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1c, 0x0a, 0x09, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x09, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x22, 0x13, 0x0a,
	0x11, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x22, 0x0f, 0x0a, 0x0d, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0x75, 0x0a, 0x0b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x24, 0x0a, 0x0d, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x56, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x41, 0x72, 0x67, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x41, 0x72, 0x67, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x53,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x73, 0x2a, 0x47, 0x0a, 0x0e, 0x52, 0x65,
	0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x08, 0x0a, 0x04,
	0x44, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x13, 0x0a, 0x0f, 0x53, 0x48, 0x41, 0x32, 0x35, 0x36,
	0x5f, 0x52, 0x45, 0x51, 0x55, 0x49, 0x52, 0x45, 0x44, 0x10, 0x01, 0x12, 0x16, 0x0a, 0x12, 0x46,
	0x55, 0x4c, 0x4c, 0x5f, 0x43, 0x4f, 0x50, 0x59, 0x5f, 0x52, 0x45, 0x51, 0x55, 0x49, 0x52, 0x45,
	0x44, 0x10, 0x02, 0x32, 0x9f, 0x03, 0x0a, 0x12, 0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x6b, 0x0a, 0x17, 0x53, 0x74,
	0x61, 0x72, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x27, 0x2e, 0x70, 0x6f, 0x70, 0x63, 0x6f, 0x72, 0x6e, 0x2e,
	0x53, 0x74, 0x61, 0x72, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25,
	0x2e, 0x70, 0x6f, 0x70, 0x63, 0x6f, 0x72, 0x6e, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x43, 0x6f,
	0x6d, 0x70, 0x69, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x47, 0x0a, 0x0c, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x66, 0x65, 0x72, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x17, 0x2e, 0x70, 0x6f, 0x70, 0x63, 0x6f, 0x72,
	0x6e, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x6e,
	0x1a, 0x18, 0x2e, 0x70, 0x6f, 0x70, 0x63, 0x6f, 0x72, 0x6e, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x66, 0x65, 0x72, 0x46, 0x69, 0x6c, 0x65, 0x4f, 0x75, 0x74, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01,
	0x12, 0x4d, 0x0a, 0x0d, 0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x65, 0x53, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x12, 0x1d, 0x2e, 0x70, 0x6f, 0x70, 0x63, 0x6f, 0x72, 0x6e, 0x2e, 0x43, 0x6f, 0x6d, 0x70,
	0x69, 0x6c, 0x65, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1b, 0x2e, 0x70, 0x6f, 0x70, 0x63, 0x6f, 0x72, 0x6e, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x69,
	0x6c, 0x65, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12,
	0x4a, 0x0a, 0x0c, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12,
	0x1c, 0x2e, 0x70, 0x6f, 0x70, 0x63, 0x6f, 0x72, 0x6e, 0x2e, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x53,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e,
	0x70, 0x6f, 0x70, 0x63, 0x6f, 0x72, 0x6e, 0x2e, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x53, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x38, 0x0a, 0x06, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x16, 0x2e, 0x70, 0x6f, 0x70, 0x63, 0x6f, 0x72, 0x6e, 0x2e,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e,
	0x70, 0x6f, 0x70, 0x63, 0x6f, 0x72, 0x6e, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x30, 0x5a, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x41, 0x6c, 0x65, 0x78, 0x4b, 0x30, 0x2f, 0x70, 0x6f, 0x70, 0x63, 0x6f,
	0x72, 0x6e, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x70, 0x6f, 0x70, 0x63, 0x6f, 0x72, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_proto_v1_compilation_server_proto_rawDescOnce sync.Once
	file_api_proto_v1_compilation_server_proto_rawDescData = file_api_proto_v1_compilation_server_proto_rawDesc
)

func file_api_proto_v1_compilation_server_proto_rawDescGZIP() []byte {
	file_api_proto_v1_compilation_server_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_compilation_server_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_v1_compilation_server_proto_rawDescData)
	})
	return file_api_proto_v1_compilation_server_proto_rawDescData
}

var file_api_proto_v1_compilation_server_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_v1_compilation_server_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_api_proto_v1_compilation_server_proto_goTypes = []interface{}{
	(RequiredStatus)(0),                    // 0: popcorn.RequiredStatus
	(*SHA256Message)(nil),                  // 1: popcorn.SHA256Message
	(*FileMetadata)(nil),                   // 2: popcorn.FileMetadata
	(*StartCompilationSessionRequest)(nil), // 3: popcorn.StartCompilationSessionRequest
	(*RequiredFile)(nil),                   // 4: popcorn.RequiredFile
	(*StartCompilationSessionReply)(nil),   // 5: popcorn.StartCompilationSessionReply
	(*TransferFileIn)(nil),                 // 6: popcorn.TransferFileIn
	(*TransferFileOut)(nil),                // 7: popcorn.TransferFileOut
	(*CompileSourceRequest)(nil),           // 8: popcorn.CompileSourceRequest
	(*CompileSourceReply)(nil),             // 9: popcorn.CompileSourceReply
	(*CloseSessionRequest)(nil),            // 10: popcorn.CloseSessionRequest
	(*CloseSessionReply)(nil),              // 11: popcorn.CloseSessionReply
	(*StatusRequest)(nil),                  // 12: popcorn.StatusRequest
	(*StatusReply)(nil),                    // 13: popcorn.StatusReply
	(*TransferFileIn_StreamHeader)(nil),    // 14: popcorn.TransferFileIn.StreamHeader
}
var file_api_proto_v1_compilation_server_proto_depIdxs = []int32{
	1,  // 0: popcorn.StartCompilationSessionRequest.UserID:type_name -> popcorn.SHA256Message
	2,  // 1: popcorn.StartCompilationSessionRequest.RequiredHeaders:type_name -> popcorn.FileMetadata
	0,  // 2: popcorn.RequiredFile.Status:type_name -> popcorn.RequiredStatus
	4,  // 3: popcorn.StartCompilationSessionReply.RequiredFiles:type_name -> popcorn.RequiredFile
	14, // 4: popcorn.TransferFileIn.Header:type_name -> popcorn.TransferFileIn.StreamHeader
	0,  // 5: popcorn.TransferFileOut.status:type_name -> popcorn.RequiredStatus
	1,  // 6: popcorn.TransferFileIn.StreamHeader.FileSHA256:type_name -> popcorn.SHA256Message
	3,  // 7: popcorn.CompilationService.StartCompilationSession:input_type -> popcorn.StartCompilationSessionRequest
	6,  // 8: popcorn.CompilationService.TransferFile:input_type -> popcorn.TransferFileIn
	8,  // 9: popcorn.CompilationService.CompileSource:input_type -> popcorn.CompileSourceRequest
	10, // 10: popcorn.CompilationService.CloseSession:input_type -> popcorn.CloseSessionRequest
	12, // 11: popcorn.CompilationService.Status:input_type -> popcorn.StatusRequest
	5,  // 12: popcorn.CompilationService.StartCompilationSession:output_type -> popcorn.StartCompilationSessionReply
	7,  // 13: popcorn.CompilationService.TransferFile:output_type -> popcorn.TransferFileOut
	9,  // 14: popcorn.CompilationService.CompileSource:output_type -> popcorn.CompileSourceReply
	11, // 15: popcorn.CompilationService.CloseSession:output_type -> popcorn.CloseSessionReply
	13, // 16: popcorn.CompilationService.Status:output_type -> popcorn.StatusReply
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_api_proto_v1_compilation_server_proto_init() }
func file_api_proto_v1_compilation_server_proto_init() {
	if File_api_proto_v1_compilation_server_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_proto_v1_compilation_server_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SHA256Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_v1_compilation_server_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileMetadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_v1_compilation_server_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartCompilationSessionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_v1_compilation_server_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequiredFile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_v1_compilation_server_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartCompilationSessionReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_v1_compilation_server_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransferFileIn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_v1_compilation_server_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransferFileOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_v1_compilation_server_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompileSourceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_v1_compilation_server_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompileSourceReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_v1_compilation_server_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CloseSessionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_v1_compilation_server_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CloseSessionReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_v1_compilation_server_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_v1_compilation_server_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatusReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_v1_compilation_server_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransferFileIn_StreamHeader); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_api_proto_v1_compilation_server_proto_msgTypes[5].OneofWrappers = []interface{}{
		(*TransferFileIn_Header)(nil),
		(*TransferFileIn_FileBodyChunk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_v1_compilation_server_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_v1_compilation_server_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_compilation_server_proto_depIdxs,
		EnumInfos:         file_api_proto_v1_compilation_server_proto_enumTypes,
		MessageInfos:      file_api_proto_v1_compilation_server_proto_msgTypes,
	}.Build()
	File_api_proto_v1_compilation_server_proto = out.File
	file_api_proto_v1_compilation_server_proto_rawDesc = nil
	file_api_proto_v1_compilation_server_proto_goTypes = nil
	file_api_proto_v1_compilation_server_proto_depIdxs = nil
}
