// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.6.1
// source: api/proto/v1/compilation-server.proto

package popcorn

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ClientIdentifier struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MachineID  string `protobuf:"bytes,1,opt,name=MachineID,proto3" json:"MachineID,omitempty"`
	MacAddress string `protobuf:"bytes,2,opt,name=MacAddress,proto3" json:"MacAddress,omitempty"`
	UserName   string `protobuf:"bytes,3,opt,name=UserName,proto3" json:"UserName,omitempty"`
	Pid        int32  `protobuf:"varint,4,opt,name=Pid,proto3" json:"Pid,omitempty"`
}

func (x *ClientIdentifier) Reset() {
	*x = ClientIdentifier{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_v1_compilation_server_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientIdentifier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientIdentifier) ProtoMessage() {}

func (x *ClientIdentifier) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_compilation_server_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientIdentifier.ProtoReflect.Descriptor instead.
func (*ClientIdentifier) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_compilation_server_proto_rawDescGZIP(), []int{0}
}

func (x *ClientIdentifier) GetMachineID() string {
	if x != nil {
		return x.MachineID
	}
	return ""
}

func (x *ClientIdentifier) GetMacAddress() string {
	if x != nil {
		return x.MacAddress
	}
	return ""
}

func (x *ClientIdentifier) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *ClientIdentifier) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

type HeaderClientMeta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FilePath string `protobuf:"bytes,1,opt,name=FilePath,proto3" json:"FilePath,omitempty"`
	MTime    int64  `protobuf:"varint,2,opt,name=MTime,proto3" json:"MTime,omitempty"`
}

func (x *HeaderClientMeta) Reset() {
	*x = HeaderClientMeta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_v1_compilation_server_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeaderClientMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeaderClientMeta) ProtoMessage() {}

func (x *HeaderClientMeta) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_compilation_server_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeaderClientMeta.ProtoReflect.Descriptor instead.
func (*HeaderClientMeta) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_compilation_server_proto_rawDescGZIP(), []int{1}
}

func (x *HeaderClientMeta) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *HeaderClientMeta) GetMTime() int64 {
	if x != nil {
		return x.MTime
	}
	return 0
}

type CopyHeadersFromClientCacheRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientID                   *ClientIdentifier   `protobuf:"bytes,1,opt,name=ClientID,proto3" json:"ClientID,omitempty"`
	ClientHeaders              []*HeaderClientMeta `protobuf:"bytes,2,rep,name=ClientHeaders,proto3" json:"ClientHeaders,omitempty"`
	ClearEnvironmentBeforeCopy bool                `protobuf:"varint,3,opt,name=ClearEnvironmentBeforeCopy,proto3" json:"ClearEnvironmentBeforeCopy,omitempty"`
}

func (x *CopyHeadersFromClientCacheRequest) Reset() {
	*x = CopyHeadersFromClientCacheRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_v1_compilation_server_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CopyHeadersFromClientCacheRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyHeadersFromClientCacheRequest) ProtoMessage() {}

func (x *CopyHeadersFromClientCacheRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_compilation_server_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyHeadersFromClientCacheRequest.ProtoReflect.Descriptor instead.
func (*CopyHeadersFromClientCacheRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_compilation_server_proto_rawDescGZIP(), []int{2}
}

func (x *CopyHeadersFromClientCacheRequest) GetClientID() *ClientIdentifier {
	if x != nil {
		return x.ClientID
	}
	return nil
}

func (x *CopyHeadersFromClientCacheRequest) GetClientHeaders() []*HeaderClientMeta {
	if x != nil {
		return x.ClientHeaders
	}
	return nil
}

func (x *CopyHeadersFromClientCacheRequest) GetClearEnvironmentBeforeCopy() bool {
	if x != nil {
		return x.ClearEnvironmentBeforeCopy
	}
	return false
}

type CopyHeadersFromClientCacheReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MissedHeaderIndex int32 `protobuf:"varint,1,opt,name=MissedHeaderIndex,proto3" json:"MissedHeaderIndex,omitempty"`
	FullCopyRequired  bool  `protobuf:"varint,2,opt,name=FullCopyRequired,proto3" json:"FullCopyRequired,omitempty"`
}

func (x *CopyHeadersFromClientCacheReply) Reset() {
	*x = CopyHeadersFromClientCacheReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_v1_compilation_server_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CopyHeadersFromClientCacheReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyHeadersFromClientCacheReply) ProtoMessage() {}

func (x *CopyHeadersFromClientCacheReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_compilation_server_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyHeadersFromClientCacheReply.ProtoReflect.Descriptor instead.
func (*CopyHeadersFromClientCacheReply) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_compilation_server_proto_rawDescGZIP(), []int{3}
}

func (x *CopyHeadersFromClientCacheReply) GetMissedHeaderIndex() int32 {
	if x != nil {
		return x.MissedHeaderIndex
	}
	return 0
}

func (x *CopyHeadersFromClientCacheReply) GetFullCopyRequired() bool {
	if x != nil {
		return x.FullCopyRequired
	}
	return false
}

type HeaderGlobalMeta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientMeta *HeaderClientMeta `protobuf:"bytes,1,opt,name=ClientMeta,proto3" json:"ClientMeta,omitempty"`
	SHA256Sum  string            `protobuf:"bytes,2,opt,name=SHA256sum,proto3" json:"SHA256sum,omitempty"`
}

func (x *HeaderGlobalMeta) Reset() {
	*x = HeaderGlobalMeta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_v1_compilation_server_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeaderGlobalMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeaderGlobalMeta) ProtoMessage() {}

func (x *HeaderGlobalMeta) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_compilation_server_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeaderGlobalMeta.ProtoReflect.Descriptor instead.
func (*HeaderGlobalMeta) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_compilation_server_proto_rawDescGZIP(), []int{4}
}

func (x *HeaderGlobalMeta) GetClientMeta() *HeaderClientMeta {
	if x != nil {
		return x.ClientMeta
	}
	return nil
}

func (x *HeaderGlobalMeta) GetSHA256Sum() string {
	if x != nil {
		return x.SHA256Sum
	}
	return ""
}

type CopyHeadersFromGlobalCacheRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientID      *ClientIdentifier   `protobuf:"bytes,1,opt,name=ClientID,proto3" json:"ClientID,omitempty"`
	GlobalHeaders []*HeaderGlobalMeta `protobuf:"bytes,2,rep,name=GlobalHeaders,proto3" json:"GlobalHeaders,omitempty"`
}

func (x *CopyHeadersFromGlobalCacheRequest) Reset() {
	*x = CopyHeadersFromGlobalCacheRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_v1_compilation_server_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CopyHeadersFromGlobalCacheRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyHeadersFromGlobalCacheRequest) ProtoMessage() {}

func (x *CopyHeadersFromGlobalCacheRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_compilation_server_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyHeadersFromGlobalCacheRequest.ProtoReflect.Descriptor instead.
func (*CopyHeadersFromGlobalCacheRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_compilation_server_proto_rawDescGZIP(), []int{5}
}

func (x *CopyHeadersFromGlobalCacheRequest) GetClientID() *ClientIdentifier {
	if x != nil {
		return x.ClientID
	}
	return nil
}

func (x *CopyHeadersFromGlobalCacheRequest) GetGlobalHeaders() []*HeaderGlobalMeta {
	if x != nil {
		return x.GlobalHeaders
	}
	return nil
}

type CopyHeadersFromGlobalCacheReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MissedHeaderIndex int32 `protobuf:"varint,1,opt,name=MissedHeaderIndex,proto3" json:"MissedHeaderIndex,omitempty"`
}

func (x *CopyHeadersFromGlobalCacheReply) Reset() {
	*x = CopyHeadersFromGlobalCacheReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_v1_compilation_server_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CopyHeadersFromGlobalCacheReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyHeadersFromGlobalCacheReply) ProtoMessage() {}

func (x *CopyHeadersFromGlobalCacheReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_compilation_server_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyHeadersFromGlobalCacheReply.ProtoReflect.Descriptor instead.
func (*CopyHeadersFromGlobalCacheReply) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_compilation_server_proto_rawDescGZIP(), []int{6}
}

func (x *CopyHeadersFromGlobalCacheReply) GetMissedHeaderIndex() int32 {
	if x != nil {
		return x.MissedHeaderIndex
	}
	return 0
}

type HeaderFullData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GlobalMeta *HeaderGlobalMeta `protobuf:"bytes,1,opt,name=GlobalMeta,proto3" json:"GlobalMeta,omitempty"`
	HeaderBody []byte            `protobuf:"bytes,2,opt,name=HeaderBody,proto3" json:"HeaderBody,omitempty"`
}

func (x *HeaderFullData) Reset() {
	*x = HeaderFullData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_v1_compilation_server_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeaderFullData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeaderFullData) ProtoMessage() {}

func (x *HeaderFullData) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_compilation_server_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeaderFullData.ProtoReflect.Descriptor instead.
func (*HeaderFullData) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_compilation_server_proto_rawDescGZIP(), []int{7}
}

func (x *HeaderFullData) GetGlobalMeta() *HeaderGlobalMeta {
	if x != nil {
		return x.GlobalMeta
	}
	return nil
}

func (x *HeaderFullData) GetHeaderBody() []byte {
	if x != nil {
		return x.HeaderBody
	}
	return nil
}

type CopyHeaderRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientID *ClientIdentifier `protobuf:"bytes,1,opt,name=ClientID,proto3" json:"ClientID,omitempty"`
	Header   *HeaderFullData   `protobuf:"bytes,2,opt,name=Header,proto3" json:"Header,omitempty"`
}

func (x *CopyHeaderRequest) Reset() {
	*x = CopyHeaderRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_v1_compilation_server_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CopyHeaderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyHeaderRequest) ProtoMessage() {}

func (x *CopyHeaderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_compilation_server_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyHeaderRequest.ProtoReflect.Descriptor instead.
func (*CopyHeaderRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_compilation_server_proto_rawDescGZIP(), []int{8}
}

func (x *CopyHeaderRequest) GetClientID() *ClientIdentifier {
	if x != nil {
		return x.ClientID
	}
	return nil
}

func (x *CopyHeaderRequest) GetHeader() *HeaderFullData {
	if x != nil {
		return x.Header
	}
	return nil
}

type CopyHeaderReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CopyHeaderReply) Reset() {
	*x = CopyHeaderReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_v1_compilation_server_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CopyHeaderReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyHeaderReply) ProtoMessage() {}

func (x *CopyHeaderReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_compilation_server_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyHeaderReply.ProtoReflect.Descriptor instead.
func (*CopyHeaderReply) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_compilation_server_proto_rawDescGZIP(), []int{9}
}

type CompileSourceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientID                   *ClientIdentifier `protobuf:"bytes,1,opt,name=ClientID,proto3" json:"ClientID,omitempty"`
	FilePath                   string            `protobuf:"bytes,2,opt,name=FilePath,proto3" json:"FilePath,omitempty"`
	Compiler                   string            `protobuf:"bytes,3,opt,name=Compiler,proto3" json:"Compiler,omitempty"`
	CompilerArgs               []string          `protobuf:"bytes,4,rep,name=CompilerArgs,proto3" json:"CompilerArgs,omitempty"`
	SourceBody                 []byte            `protobuf:"bytes,5,opt,name=SourceBody,proto3" json:"SourceBody,omitempty"`
	ClearEnvironmentAfterBuild bool              `protobuf:"varint,6,opt,name=ClearEnvironmentAfterBuild,proto3" json:"ClearEnvironmentAfterBuild,omitempty"`
}

func (x *CompileSourceRequest) Reset() {
	*x = CompileSourceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_v1_compilation_server_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompileSourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompileSourceRequest) ProtoMessage() {}

func (x *CompileSourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_compilation_server_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompileSourceRequest.ProtoReflect.Descriptor instead.
func (*CompileSourceRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_compilation_server_proto_rawDescGZIP(), []int{10}
}

func (x *CompileSourceRequest) GetClientID() *ClientIdentifier {
	if x != nil {
		return x.ClientID
	}
	return nil
}

func (x *CompileSourceRequest) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *CompileSourceRequest) GetCompiler() string {
	if x != nil {
		return x.Compiler
	}
	return ""
}

func (x *CompileSourceRequest) GetCompilerArgs() []string {
	if x != nil {
		return x.CompilerArgs
	}
	return nil
}

func (x *CompileSourceRequest) GetSourceBody() []byte {
	if x != nil {
		return x.SourceBody
	}
	return nil
}

func (x *CompileSourceRequest) GetClearEnvironmentAfterBuild() bool {
	if x != nil {
		return x.ClearEnvironmentAfterBuild
	}
	return false
}

type CompileSourceReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CompilerRetCode int32  `protobuf:"varint,1,opt,name=CompilerRetCode,proto3" json:"CompilerRetCode,omitempty"`
	CompiledSource  []byte `protobuf:"bytes,2,opt,name=CompiledSource,proto3" json:"CompiledSource,omitempty"`
	CompilerStdout  []byte `protobuf:"bytes,3,opt,name=CompilerStdout,proto3" json:"CompilerStdout,omitempty"`
	CompilerStderr  []byte `protobuf:"bytes,4,opt,name=CompilerStderr,proto3" json:"CompilerStderr,omitempty"`
}

func (x *CompileSourceReply) Reset() {
	*x = CompileSourceReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_v1_compilation_server_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompileSourceReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompileSourceReply) ProtoMessage() {}

func (x *CompileSourceReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_compilation_server_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompileSourceReply.ProtoReflect.Descriptor instead.
func (*CompileSourceReply) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_compilation_server_proto_rawDescGZIP(), []int{11}
}

func (x *CompileSourceReply) GetCompilerRetCode() int32 {
	if x != nil {
		return x.CompilerRetCode
	}
	return 0
}

func (x *CompileSourceReply) GetCompiledSource() []byte {
	if x != nil {
		return x.CompiledSource
	}
	return nil
}

func (x *CompileSourceReply) GetCompilerStdout() []byte {
	if x != nil {
		return x.CompilerStdout
	}
	return nil
}

func (x *CompileSourceReply) GetCompilerStderr() []byte {
	if x != nil {
		return x.CompilerStderr
	}
	return nil
}

type ClearEnvironmentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientID *ClientIdentifier `protobuf:"bytes,1,opt,name=ClientID,proto3" json:"ClientID,omitempty"`
}

func (x *ClearEnvironmentRequest) Reset() {
	*x = ClearEnvironmentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_v1_compilation_server_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClearEnvironmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearEnvironmentRequest) ProtoMessage() {}

func (x *ClearEnvironmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_compilation_server_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearEnvironmentRequest.ProtoReflect.Descriptor instead.
func (*ClearEnvironmentRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_compilation_server_proto_rawDescGZIP(), []int{12}
}

func (x *ClearEnvironmentRequest) GetClientID() *ClientIdentifier {
	if x != nil {
		return x.ClientID
	}
	return nil
}

type ClearEnvironmentReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ClearEnvironmentReply) Reset() {
	*x = ClearEnvironmentReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_v1_compilation_server_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClearEnvironmentReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearEnvironmentReply) ProtoMessage() {}

func (x *ClearEnvironmentReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_compilation_server_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearEnvironmentReply.ProtoReflect.Descriptor instead.
func (*ClearEnvironmentReply) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_compilation_server_proto_rawDescGZIP(), []int{13}
}

type StatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_v1_compilation_server_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_compilation_server_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_compilation_server_proto_rawDescGZIP(), []int{14}
}

type StatusReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerVersion           string `protobuf:"bytes,1,opt,name=ServerVersion,proto3" json:"ServerVersion,omitempty"`
	CPUsCount               uint64 `protobuf:"varint,2,opt,name=CPUsCount,proto3" json:"CPUsCount,omitempty"`
	ActiveGoroutinesCount   uint64 `protobuf:"varint,3,opt,name=ActiveGoroutinesCount,proto3" json:"ActiveGoroutinesCount,omitempty"`
	ClientsCount            uint64 `protobuf:"varint,4,opt,name=ClientsCount,proto3" json:"ClientsCount,omitempty"`
	SystemHeadersUsedCount  uint64 `protobuf:"varint,5,opt,name=SystemHeadersUsedCount,proto3" json:"SystemHeadersUsedCount,omitempty"`
	CachedHeaderOnDiskCount uint64 `protobuf:"varint,6,opt,name=CachedHeaderOnDiskCount,proto3" json:"CachedHeaderOnDiskCount,omitempty"`
	CachedHeaderOnDiskBytes uint64 `protobuf:"varint,7,opt,name=CachedHeaderOnDiskBytes,proto3" json:"CachedHeaderOnDiskBytes,omitempty"`
	HeapAllocBytes          uint64 `protobuf:"varint,8,opt,name=HeapAllocBytes,proto3" json:"HeapAllocBytes,omitempty"`
	SystemAllocBytes        uint64 `protobuf:"varint,9,opt,name=SystemAllocBytes,proto3" json:"SystemAllocBytes,omitempty"`
	UptimeNanoseconds       uint64 `protobuf:"varint,10,opt,name=UptimeNanoseconds,proto3" json:"UptimeNanoseconds,omitempty"`
}

func (x *StatusReply) Reset() {
	*x = StatusReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_v1_compilation_server_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatusReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusReply) ProtoMessage() {}

func (x *StatusReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_compilation_server_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusReply.ProtoReflect.Descriptor instead.
func (*StatusReply) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_compilation_server_proto_rawDescGZIP(), []int{15}
}

func (x *StatusReply) GetServerVersion() string {
	if x != nil {
		return x.ServerVersion
	}
	return ""
}

func (x *StatusReply) GetCPUsCount() uint64 {
	if x != nil {
		return x.CPUsCount
	}
	return 0
}

func (x *StatusReply) GetActiveGoroutinesCount() uint64 {
	if x != nil {
		return x.ActiveGoroutinesCount
	}
	return 0
}

func (x *StatusReply) GetClientsCount() uint64 {
	if x != nil {
		return x.ClientsCount
	}
	return 0
}

func (x *StatusReply) GetSystemHeadersUsedCount() uint64 {
	if x != nil {
		return x.SystemHeadersUsedCount
	}
	return 0
}

func (x *StatusReply) GetCachedHeaderOnDiskCount() uint64 {
	if x != nil {
		return x.CachedHeaderOnDiskCount
	}
	return 0
}

func (x *StatusReply) GetCachedHeaderOnDiskBytes() uint64 {
	if x != nil {
		return x.CachedHeaderOnDiskBytes
	}
	return 0
}

func (x *StatusReply) GetHeapAllocBytes() uint64 {
	if x != nil {
		return x.HeapAllocBytes
	}
	return 0
}

func (x *StatusReply) GetSystemAllocBytes() uint64 {
	if x != nil {
		return x.SystemAllocBytes
	}
	return 0
}

func (x *StatusReply) GetUptimeNanoseconds() uint64 {
	if x != nil {
		return x.UptimeNanoseconds
	}
	return 0
}

type UpdateServerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NewBinary []byte `protobuf:"bytes,1,opt,name=NewBinary,proto3" json:"NewBinary,omitempty"`
	Password  string `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
}

func (x *UpdateServerRequest) Reset() {
	*x = UpdateServerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_v1_compilation_server_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateServerRequest) ProtoMessage() {}

func (x *UpdateServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_compilation_server_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateServerRequest.ProtoReflect.Descriptor instead.
func (*UpdateServerRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_compilation_server_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateServerRequest) GetNewBinary() []byte {
	if x != nil {
		return x.NewBinary
	}
	return nil
}

func (x *UpdateServerRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type UpdateServerReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateServerReply) Reset() {
	*x = UpdateServerReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_v1_compilation_server_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateServerReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateServerReply) ProtoMessage() {}

func (x *UpdateServerReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_compilation_server_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateServerReply.ProtoReflect.Descriptor instead.
func (*UpdateServerReply) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_compilation_server_proto_rawDescGZIP(), []int{17}
}

type RestartServerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Password string `protobuf:"bytes,1,opt,name=Password,proto3" json:"Password,omitempty"`
}

func (x *RestartServerRequest) Reset() {
	*x = RestartServerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_v1_compilation_server_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RestartServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartServerRequest) ProtoMessage() {}

func (x *RestartServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_compilation_server_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartServerRequest.ProtoReflect.Descriptor instead.
func (*RestartServerRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_compilation_server_proto_rawDescGZIP(), []int{18}
}

func (x *RestartServerRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RestartServerReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RestartServerReply) Reset() {
	*x = RestartServerReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_v1_compilation_server_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RestartServerReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartServerReply) ProtoMessage() {}

func (x *RestartServerReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_compilation_server_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartServerReply.ProtoReflect.Descriptor instead.
func (*RestartServerReply) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_compilation_server_proto_rawDescGZIP(), []int{19}
}

type DumpServerLogRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Password   string `protobuf:"bytes,1,opt,name=Password,proto3" json:"Password,omitempty"`
	BytesLimit uint64 `protobuf:"varint,2,opt,name=BytesLimit,proto3" json:"BytesLimit,omitempty"`
}

func (x *DumpServerLogRequest) Reset() {
	*x = DumpServerLogRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_v1_compilation_server_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DumpServerLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DumpServerLogRequest) ProtoMessage() {}

func (x *DumpServerLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_compilation_server_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DumpServerLogRequest.ProtoReflect.Descriptor instead.
func (*DumpServerLogRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_compilation_server_proto_rawDescGZIP(), []int{20}
}

func (x *DumpServerLogRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *DumpServerLogRequest) GetBytesLimit() uint64 {
	if x != nil {
		return x.BytesLimit
	}
	return 0
}

type DumpServerLogReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LogData []byte `protobuf:"bytes,1,opt,name=LogData,proto3" json:"LogData,omitempty"`
}

func (x *DumpServerLogReply) Reset() {
	*x = DumpServerLogReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_v1_compilation_server_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DumpServerLogReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DumpServerLogReply) ProtoMessage() {}

func (x *DumpServerLogReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_compilation_server_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DumpServerLogReply.ProtoReflect.Descriptor instead.
func (*DumpServerLogReply) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_compilation_server_proto_rawDescGZIP(), []int{21}
}

func (x *DumpServerLogReply) GetLogData() []byte {
	if x != nil {
		return x.LogData
	}
	return nil
}

var File_api_proto_v1_compilation_server_proto protoreflect.FileDescriptor

var file_api_proto_v1_compilation_server_proto_rawDesc = []byte{
	0x0a, 0x25, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x31, 0x2f, 0x63,
	0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x70, 0x6f, 0x70, 0x63, 0x6f, 0x72, 0x6e,
	0x22, 0x7e, 0x0a, 0x10, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69,
	0x66, 0x69, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65,
	0x49, 0x44, 0x12, 0x1e, 0x0a, 0x0a, 0x4d, 0x61, 0x63, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x4d, 0x61, 0x63, 0x41, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x50, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x50, 0x69, 0x64,
	0x22, 0x44, 0x0a, 0x10, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x4d, 0x65, 0x74, 0x61, 0x12, 0x1a, 0x0a, 0x08, 0x46, 0x69, 0x6c, 0x65, 0x50, 0x61, 0x74, 0x68,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x46, 0x69, 0x6c, 0x65, 0x50, 0x61, 0x74, 0x68,
	0x12, 0x14, 0x0a, 0x05, 0x4d, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x05, 0x4d, 0x54, 0x69, 0x6d, 0x65, 0x22, 0xdb, 0x01, 0x0a, 0x21, 0x43, 0x6f, 0x70, 0x79, 0x48,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x46, 0x72, 0x6f, 0x6d, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x43, 0x61, 0x63, 0x68, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x35, 0x0a, 0x08,
	0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19,
	0x2e, 0x70, 0x6f, 0x70, 0x63, 0x6f, 0x72, 0x6e, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49,
	0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x52, 0x08, 0x43, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x49, 0x44, 0x12, 0x3f, 0x0a, 0x0d, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x48, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x70, 0x6f, 0x70,
	0x63, 0x6f, 0x72, 0x6e, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x43, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x0d, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x48, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x73, 0x12, 0x3e, 0x0a, 0x1a, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x45, 0x6e, 0x76,
	0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x42, 0x65, 0x66, 0x6f, 0x72, 0x65, 0x43, 0x6f,
	0x70, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x1a, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x45,
	0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x42, 0x65, 0x66, 0x6f, 0x72, 0x65,
	0x43, 0x6f, 0x70, 0x79, 0x22, 0x7b, 0x0a, 0x1f, 0x43, 0x6f, 0x70, 0x79, 0x48, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x73, 0x46, 0x72, 0x6f, 0x6d, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x43, 0x61, 0x63,
	0x68, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x2c, 0x0a, 0x11, 0x4d, 0x69, 0x73, 0x73, 0x65,
	0x64, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x11, 0x4d, 0x69, 0x73, 0x73, 0x65, 0x64, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x2a, 0x0a, 0x10, 0x46, 0x75, 0x6c, 0x6c, 0x43, 0x6f, 0x70,
	0x79, 0x52, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x10, 0x46, 0x75, 0x6c, 0x6c, 0x43, 0x6f, 0x70, 0x79, 0x52, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65,
	0x64, 0x22, 0x6b, 0x0a, 0x10, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x47, 0x6c, 0x6f, 0x62, 0x61,
	0x6c, 0x4d, 0x65, 0x74, 0x61, 0x12, 0x39, 0x0a, 0x0a, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d,
	0x65, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x70, 0x6f, 0x70, 0x63,
	0x6f, 0x72, 0x6e, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x4d, 0x65, 0x74, 0x61, 0x52, 0x0a, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x74, 0x61,
	0x12, 0x1c, 0x0a, 0x09, 0x53, 0x48, 0x41, 0x32, 0x35, 0x36, 0x73, 0x75, 0x6d, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x53, 0x48, 0x41, 0x32, 0x35, 0x36, 0x73, 0x75, 0x6d, 0x22, 0x9b,
	0x01, 0x0a, 0x21, 0x43, 0x6f, 0x70, 0x79, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x46, 0x72,
	0x6f, 0x6d, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x43, 0x61, 0x63, 0x68, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x35, 0x0a, 0x08, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x70, 0x6f, 0x70, 0x63, 0x6f, 0x72, 0x6e,
	0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65,
	0x72, 0x52, 0x08, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x12, 0x3f, 0x0a, 0x0d, 0x47,
	0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x19, 0x2e, 0x70, 0x6f, 0x70, 0x63, 0x6f, 0x72, 0x6e, 0x2e, 0x48, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x0d, 0x47,
	0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x22, 0x4f, 0x0a, 0x1f,
	0x43, 0x6f, 0x70, 0x79, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x46, 0x72, 0x6f, 0x6d, 0x47,
	0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x43, 0x61, 0x63, 0x68, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x2c, 0x0a, 0x11, 0x4d, 0x69, 0x73, 0x73, 0x65, 0x64, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x49,
	0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x11, 0x4d, 0x69, 0x73, 0x73,
	0x65, 0x64, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x22, 0x6b, 0x0a,
	0x0e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x46, 0x75, 0x6c, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x12,
	0x39, 0x0a, 0x0a, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x4d, 0x65, 0x74, 0x61, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x70, 0x6f, 0x70, 0x63, 0x6f, 0x72, 0x6e, 0x2e, 0x48, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x0a,
	0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x4d, 0x65, 0x74, 0x61, 0x12, 0x1e, 0x0a, 0x0a, 0x48, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x42, 0x6f, 0x64, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a,
	0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x42, 0x6f, 0x64, 0x79, 0x22, 0x7b, 0x0a, 0x11, 0x43, 0x6f,
	0x70, 0x79, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x35, 0x0a, 0x08, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x19, 0x2e, 0x70, 0x6f, 0x70, 0x63, 0x6f, 0x72, 0x6e, 0x2e, 0x43, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x52, 0x08, 0x43, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x12, 0x2f, 0x0a, 0x06, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x70, 0x6f, 0x70, 0x63, 0x6f, 0x72, 0x6e,
	0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x46, 0x75, 0x6c, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x52,
	0x06, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x22, 0x11, 0x0a, 0x0f, 0x43, 0x6f, 0x70, 0x79, 0x48,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x89, 0x02, 0x0a, 0x14, 0x43,
	0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x65, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x35, 0x0a, 0x08, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x70, 0x6f, 0x70, 0x63, 0x6f, 0x72, 0x6e, 0x2e,
	0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72,
	0x52, 0x08, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x46, 0x69,
	0x6c, 0x65, 0x50, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x46, 0x69,
	0x6c, 0x65, 0x50, 0x61, 0x74, 0x68, 0x12, 0x1a, 0x0a, 0x08, 0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c,
	0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c,
	0x65, 0x72, 0x12, 0x22, 0x0a, 0x0c, 0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x65, 0x72, 0x41, 0x72,
	0x67, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0c, 0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c,
	0x65, 0x72, 0x41, 0x72, 0x67, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x42, 0x6f, 0x64, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x53, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x3e, 0x0a, 0x1a, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x45,
	0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x41, 0x66, 0x74, 0x65, 0x72, 0x42,
	0x75, 0x69, 0x6c, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x1a, 0x43, 0x6c, 0x65, 0x61,
	0x72, 0x45, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x41, 0x66, 0x74, 0x65,
	0x72, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x22, 0xb6, 0x01, 0x0a, 0x12, 0x43, 0x6f, 0x6d, 0x70, 0x69,
	0x6c, 0x65, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x28, 0x0a,
	0x0f, 0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x65, 0x72, 0x52, 0x65, 0x74, 0x43, 0x6f, 0x64, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0f, 0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x65, 0x72,
	0x52, 0x65, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x43, 0x6f, 0x6d, 0x70, 0x69,
	0x6c, 0x65, 0x64, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x0e, 0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x65, 0x64, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12,
	0x26, 0x0a, 0x0e, 0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x65, 0x72, 0x53, 0x74, 0x64, 0x6f, 0x75,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0e, 0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x65,
	0x72, 0x53, 0x74, 0x64, 0x6f, 0x75, 0x74, 0x12, 0x26, 0x0a, 0x0e, 0x43, 0x6f, 0x6d, 0x70, 0x69,
	0x6c, 0x65, 0x72, 0x53, 0x74, 0x64, 0x65, 0x72, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x0e, 0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x65, 0x72, 0x53, 0x74, 0x64, 0x65, 0x72, 0x72, 0x22,
	0x50, 0x0a, 0x17, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x45, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d,
	0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x35, 0x0a, 0x08, 0x43, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x70,
	0x6f, 0x70, 0x63, 0x6f, 0x72, 0x6e, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x65,
	0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x52, 0x08, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49,
	0x44, 0x22, 0x17, 0x0a, 0x15, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x45, 0x6e, 0x76, 0x69, 0x72, 0x6f,
	0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x0f, 0x0a, 0x0d, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0xd9, 0x03, 0x0a, 0x0b,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x24, 0x0a, 0x0d, 0x53,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0d, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x43, 0x50, 0x55, 0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x43, 0x50, 0x55, 0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12,
	0x34, 0x0a, 0x15, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x47, 0x6f, 0x72, 0x6f, 0x75, 0x74, 0x69,
	0x6e, 0x65, 0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x15,
	0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x47, 0x6f, 0x72, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x65, 0x73,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x73,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0c, 0x43, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x36, 0x0a, 0x16, 0x53, 0x79, 0x73,
	0x74, 0x65, 0x6d, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x55, 0x73, 0x65, 0x64, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x16, 0x53, 0x79, 0x73, 0x74, 0x65,
	0x6d, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x55, 0x73, 0x65, 0x64, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x12, 0x38, 0x0a, 0x17, 0x43, 0x61, 0x63, 0x68, 0x65, 0x64, 0x48, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x4f, 0x6e, 0x44, 0x69, 0x73, 0x6b, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x17, 0x43, 0x61, 0x63, 0x68, 0x65, 0x64, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x4f, 0x6e, 0x44, 0x69, 0x73, 0x6b, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x38, 0x0a, 0x17, 0x43,
	0x61, 0x63, 0x68, 0x65, 0x64, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x4f, 0x6e, 0x44, 0x69, 0x73,
	0x6b, 0x42, 0x79, 0x74, 0x65, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x04, 0x52, 0x17, 0x43, 0x61,
	0x63, 0x68, 0x65, 0x64, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x4f, 0x6e, 0x44, 0x69, 0x73, 0x6b,
	0x42, 0x79, 0x74, 0x65, 0x73, 0x12, 0x26, 0x0a, 0x0e, 0x48, 0x65, 0x61, 0x70, 0x41, 0x6c, 0x6c,
	0x6f, 0x63, 0x42, 0x79, 0x74, 0x65, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0e, 0x48,
	0x65, 0x61, 0x70, 0x41, 0x6c, 0x6c, 0x6f, 0x63, 0x42, 0x79, 0x74, 0x65, 0x73, 0x12, 0x2a, 0x0a,
	0x10, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x41, 0x6c, 0x6c, 0x6f, 0x63, 0x42, 0x79, 0x74, 0x65,
	0x73, 0x18, 0x09, 0x20, 0x01, 0x28, 0x04, 0x52, 0x10, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x41,
	0x6c, 0x6c, 0x6f, 0x63, 0x42, 0x79, 0x74, 0x65, 0x73, 0x12, 0x2c, 0x0a, 0x11, 0x55, 0x70, 0x74,
	0x69, 0x6d, 0x65, 0x4e, 0x61, 0x6e, 0x6f, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x18, 0x0a,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x11, 0x55, 0x70, 0x74, 0x69, 0x6d, 0x65, 0x4e, 0x61, 0x6e, 0x6f,
	0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x22, 0x4f, 0x0a, 0x13, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c,
	0x0a, 0x09, 0x4e, 0x65, 0x77, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x09, 0x4e, 0x65, 0x77, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x12, 0x1a, 0x0a, 0x08,
	0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x13, 0x0a, 0x11, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x32, 0x0a,
	0x14, 0x52, 0x65, 0x73, 0x74, 0x61, 0x72, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x22, 0x14, 0x0a, 0x12, 0x52, 0x65, 0x73, 0x74, 0x61, 0x72, 0x74, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x52, 0x0a, 0x14, 0x44, 0x75, 0x6d, 0x70, 0x53,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1a, 0x0a, 0x08, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x42,
	0x79, 0x74, 0x65, 0x73, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x0a, 0x42, 0x79, 0x74, 0x65, 0x73, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x2e, 0x0a, 0x12, 0x44,
	0x75, 0x6d, 0x70, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x18, 0x0a, 0x07, 0x4c, 0x6f, 0x67, 0x44, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x07, 0x4c, 0x6f, 0x67, 0x44, 0x61, 0x74, 0x61, 0x32, 0x95, 0x06, 0x0a, 0x12,
	0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x76, 0x0a, 0x1a, 0x43, 0x6f, 0x70, 0x79, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x73, 0x46, 0x72, 0x6f, 0x6d, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x43, 0x61, 0x63, 0x68, 0x65,
	0x12, 0x2a, 0x2e, 0x70, 0x6f, 0x70, 0x63, 0x6f, 0x72, 0x6e, 0x2e, 0x43, 0x6f, 0x70, 0x79, 0x48,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x46, 0x72, 0x6f, 0x6d, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x43, 0x61, 0x63, 0x68, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e, 0x70,
	0x6f, 0x70, 0x63, 0x6f, 0x72, 0x6e, 0x2e, 0x43, 0x6f, 0x70, 0x79, 0x48, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x73, 0x46, 0x72, 0x6f, 0x6d, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x43, 0x61, 0x63, 0x68,
	0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x30, 0x01, 0x12, 0x76, 0x0a, 0x1a, 0x43, 0x6f,
	0x70, 0x79, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x46, 0x72, 0x6f, 0x6d, 0x47, 0x6c, 0x6f,
	0x62, 0x61, 0x6c, 0x43, 0x61, 0x63, 0x68, 0x65, 0x12, 0x2a, 0x2e, 0x70, 0x6f, 0x70, 0x63, 0x6f,
	0x72, 0x6e, 0x2e, 0x43, 0x6f, 0x70, 0x79, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x46, 0x72,
	0x6f, 0x6d, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x43, 0x61, 0x63, 0x68, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e, 0x70, 0x6f, 0x70, 0x63, 0x6f, 0x72, 0x6e, 0x2e, 0x43,
	0x6f, 0x70, 0x79, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x46, 0x72, 0x6f, 0x6d, 0x47, 0x6c,
	0x6f, 0x62, 0x61, 0x6c, 0x43, 0x61, 0x63, 0x68, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00,
	0x30, 0x01, 0x12, 0x44, 0x0a, 0x0a, 0x43, 0x6f, 0x70, 0x79, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x12, 0x1a, 0x2e, 0x70, 0x6f, 0x70, 0x63, 0x6f, 0x72, 0x6e, 0x2e, 0x43, 0x6f, 0x70, 0x79, 0x48,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x70,
	0x6f, 0x70, 0x63, 0x6f, 0x72, 0x6e, 0x2e, 0x43, 0x6f, 0x70, 0x79, 0x48, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x4d, 0x0a, 0x0d, 0x43, 0x6f, 0x6d, 0x70,
	0x69, 0x6c, 0x65, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x1d, 0x2e, 0x70, 0x6f, 0x70, 0x63,
	0x6f, 0x72, 0x6e, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x65, 0x53, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x70, 0x6f, 0x70, 0x63, 0x6f,
	0x72, 0x6e, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x65, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x56, 0x0a, 0x10, 0x43, 0x6c, 0x65, 0x61, 0x72,
	0x45, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x20, 0x2e, 0x70, 0x6f,
	0x70, 0x63, 0x6f, 0x72, 0x6e, 0x2e, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x45, 0x6e, 0x76, 0x69, 0x72,
	0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e,
	0x70, 0x6f, 0x70, 0x63, 0x6f, 0x72, 0x6e, 0x2e, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x45, 0x6e, 0x76,
	0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12,
	0x38, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x16, 0x2e, 0x70, 0x6f, 0x70, 0x63,
	0x6f, 0x72, 0x6e, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x14, 0x2e, 0x70, 0x6f, 0x70, 0x63, 0x6f, 0x72, 0x6e, 0x2e, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x4a, 0x0a, 0x0c, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x1c, 0x2e, 0x70, 0x6f, 0x70, 0x63,
	0x6f, 0x72, 0x6e, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x70, 0x6f, 0x70, 0x63, 0x6f, 0x72,
	0x6e, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x4d, 0x0a, 0x0d, 0x52, 0x65, 0x73, 0x74, 0x61, 0x72, 0x74,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x1d, 0x2e, 0x70, 0x6f, 0x70, 0x63, 0x6f, 0x72, 0x6e,
	0x2e, 0x52, 0x65, 0x73, 0x74, 0x61, 0x72, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x70, 0x6f, 0x70, 0x63, 0x6f, 0x72, 0x6e, 0x2e,
	0x52, 0x65, 0x73, 0x74, 0x61, 0x72, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x22, 0x00, 0x12, 0x4d, 0x0a, 0x0d, 0x44, 0x75, 0x6d, 0x70, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x4c, 0x6f, 0x67, 0x12, 0x1d, 0x2e, 0x70, 0x6f, 0x70, 0x63, 0x6f, 0x72, 0x6e, 0x2e,
	0x44, 0x75, 0x6d, 0x70, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x70, 0x6f, 0x70, 0x63, 0x6f, 0x72, 0x6e, 0x2e, 0x44,
	0x75, 0x6d, 0x70, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x22, 0x00, 0x42, 0x30, 0x5a, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x41, 0x6c, 0x65, 0x78, 0x4b, 0x30, 0x2f, 0x70, 0x6f, 0x70, 0x63, 0x6f, 0x72, 0x6e,
	0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x6f,
	0x70, 0x63, 0x6f, 0x72, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_proto_v1_compilation_server_proto_rawDescOnce sync.Once
	file_api_proto_v1_compilation_server_proto_rawDescData = file_api_proto_v1_compilation_server_proto_rawDesc
)

func file_api_proto_v1_compilation_server_proto_rawDescGZIP() []byte {
	file_api_proto_v1_compilation_server_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_compilation_server_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_v1_compilation_server_proto_rawDescData)
	})
	return file_api_proto_v1_compilation_server_proto_rawDescData
}

var file_api_proto_v1_compilation_server_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_api_proto_v1_compilation_server_proto_goTypes = []interface{}{
	(*ClientIdentifier)(nil),                  // 0: popcorn.ClientIdentifier
	(*HeaderClientMeta)(nil),                  // 1: popcorn.HeaderClientMeta
	(*CopyHeadersFromClientCacheRequest)(nil), // 2: popcorn.CopyHeadersFromClientCacheRequest
	(*CopyHeadersFromClientCacheReply)(nil),   // 3: popcorn.CopyHeadersFromClientCacheReply
	(*HeaderGlobalMeta)(nil),                  // 4: popcorn.HeaderGlobalMeta
	(*CopyHeadersFromGlobalCacheRequest)(nil), // 5: popcorn.CopyHeadersFromGlobalCacheRequest
	(*CopyHeadersFromGlobalCacheReply)(nil),   // 6: popcorn.CopyHeadersFromGlobalCacheReply
	(*HeaderFullData)(nil),                    // 7: popcorn.HeaderFullData
	(*CopyHeaderRequest)(nil),                 // 8: popcorn.CopyHeaderRequest
	(*CopyHeaderReply)(nil),                   // 9: popcorn.CopyHeaderReply
	(*CompileSourceRequest)(nil),              // 10: popcorn.CompileSourceRequest
	(*CompileSourceReply)(nil),                // 11: popcorn.CompileSourceReply
	(*ClearEnvironmentRequest)(nil),           // 12: popcorn.ClearEnvironmentRequest
	(*ClearEnvironmentReply)(nil),             // 13: popcorn.ClearEnvironmentReply
	(*StatusRequest)(nil),                     // 14: popcorn.StatusRequest
	(*StatusReply)(nil),                       // 15: popcorn.StatusReply
	(*UpdateServerRequest)(nil),               // 16: popcorn.UpdateServerRequest
	(*UpdateServerReply)(nil),                 // 17: popcorn.UpdateServerReply
	(*RestartServerRequest)(nil),              // 18: popcorn.RestartServerRequest
	(*RestartServerReply)(nil),                // 19: popcorn.RestartServerReply
	(*DumpServerLogRequest)(nil),              // 20: popcorn.DumpServerLogRequest
	(*DumpServerLogReply)(nil),                // 21: popcorn.DumpServerLogReply
}
var file_api_proto_v1_compilation_server_proto_depIdxs = []int32{
	0,  // 0: popcorn.CopyHeadersFromClientCacheRequest.ClientID:type_name -> popcorn.ClientIdentifier
	1,  // 1: popcorn.CopyHeadersFromClientCacheRequest.ClientHeaders:type_name -> popcorn.HeaderClientMeta
	1,  // 2: popcorn.HeaderGlobalMeta.ClientMeta:type_name -> popcorn.HeaderClientMeta
	0,  // 3: popcorn.CopyHeadersFromGlobalCacheRequest.ClientID:type_name -> popcorn.ClientIdentifier
	4,  // 4: popcorn.CopyHeadersFromGlobalCacheRequest.GlobalHeaders:type_name -> popcorn.HeaderGlobalMeta
	4,  // 5: popcorn.HeaderFullData.GlobalMeta:type_name -> popcorn.HeaderGlobalMeta
	0,  // 6: popcorn.CopyHeaderRequest.ClientID:type_name -> popcorn.ClientIdentifier
	7,  // 7: popcorn.CopyHeaderRequest.Header:type_name -> popcorn.HeaderFullData
	0,  // 8: popcorn.CompileSourceRequest.ClientID:type_name -> popcorn.ClientIdentifier
	0,  // 9: popcorn.ClearEnvironmentRequest.ClientID:type_name -> popcorn.ClientIdentifier
	2,  // 10: popcorn.CompilationService.CopyHeadersFromClientCache:input_type -> popcorn.CopyHeadersFromClientCacheRequest
	5,  // 11: popcorn.CompilationService.CopyHeadersFromGlobalCache:input_type -> popcorn.CopyHeadersFromGlobalCacheRequest
	8,  // 12: popcorn.CompilationService.CopyHeader:input_type -> popcorn.CopyHeaderRequest
	10, // 13: popcorn.CompilationService.CompileSource:input_type -> popcorn.CompileSourceRequest
	12, // 14: popcorn.CompilationService.ClearEnvironment:input_type -> popcorn.ClearEnvironmentRequest
	14, // 15: popcorn.CompilationService.Status:input_type -> popcorn.StatusRequest
	16, // 16: popcorn.CompilationService.UpdateServer:input_type -> popcorn.UpdateServerRequest
	18, // 17: popcorn.CompilationService.RestartServer:input_type -> popcorn.RestartServerRequest
	20, // 18: popcorn.CompilationService.DumpServerLog:input_type -> popcorn.DumpServerLogRequest
	3,  // 19: popcorn.CompilationService.CopyHeadersFromClientCache:output_type -> popcorn.CopyHeadersFromClientCacheReply
	6,  // 20: popcorn.CompilationService.CopyHeadersFromGlobalCache:output_type -> popcorn.CopyHeadersFromGlobalCacheReply
	9,  // 21: popcorn.CompilationService.CopyHeader:output_type -> popcorn.CopyHeaderReply
	11, // 22: popcorn.CompilationService.CompileSource:output_type -> popcorn.CompileSourceReply
	13, // 23: popcorn.CompilationService.ClearEnvironment:output_type -> popcorn.ClearEnvironmentReply
	15, // 24: popcorn.CompilationService.Status:output_type -> popcorn.StatusReply
	17, // 25: popcorn.CompilationService.UpdateServer:output_type -> popcorn.UpdateServerReply
	19, // 26: popcorn.CompilationService.RestartServer:output_type -> popcorn.RestartServerReply
	21, // 27: popcorn.CompilationService.DumpServerLog:output_type -> popcorn.DumpServerLogReply
	19, // [19:28] is the sub-list for method output_type
	10, // [10:19] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_api_proto_v1_compilation_server_proto_init() }
func file_api_proto_v1_compilation_server_proto_init() {
	if File_api_proto_v1_compilation_server_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_proto_v1_compilation_server_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientIdentifier); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_v1_compilation_server_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeaderClientMeta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_v1_compilation_server_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CopyHeadersFromClientCacheRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_v1_compilation_server_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CopyHeadersFromClientCacheReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_v1_compilation_server_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeaderGlobalMeta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_v1_compilation_server_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CopyHeadersFromGlobalCacheRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_v1_compilation_server_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CopyHeadersFromGlobalCacheReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_v1_compilation_server_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeaderFullData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_v1_compilation_server_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CopyHeaderRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_v1_compilation_server_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CopyHeaderReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_v1_compilation_server_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompileSourceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_v1_compilation_server_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompileSourceReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_v1_compilation_server_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClearEnvironmentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_v1_compilation_server_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClearEnvironmentReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_v1_compilation_server_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_v1_compilation_server_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatusReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_v1_compilation_server_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateServerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_v1_compilation_server_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateServerReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_v1_compilation_server_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RestartServerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_v1_compilation_server_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RestartServerReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_v1_compilation_server_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DumpServerLogRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_v1_compilation_server_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DumpServerLogReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_v1_compilation_server_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_v1_compilation_server_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_compilation_server_proto_depIdxs,
		MessageInfos:      file_api_proto_v1_compilation_server_proto_msgTypes,
	}.Build()
	File_api_proto_v1_compilation_server_proto = out.File
	file_api_proto_v1_compilation_server_proto_rawDesc = nil
	file_api_proto_v1_compilation_server_proto_goTypes = nil
	file_api_proto_v1_compilation_server_proto_depIdxs = nil
}
