// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.6.1
// source: api/proto/v1/compilation-server.proto

package popcorn

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type SHA256Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	B0_7   uint64 `protobuf:"fixed64,1,opt,name=B0_7,json=B07,proto3" json:"B0_7,omitempty"`
	B8_15  uint64 `protobuf:"fixed64,2,opt,name=B8_15,json=B815,proto3" json:"B8_15,omitempty"`
	B16_23 uint64 `protobuf:"fixed64,3,opt,name=B16_23,json=B1623,proto3" json:"B16_23,omitempty"`
	B24_31 uint64 `protobuf:"fixed64,4,opt,name=B24_31,json=B2431,proto3" json:"B24_31,omitempty"`
}

func (x *SHA256Message) Reset() {
	*x = SHA256Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_v1_compilation_server_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SHA256Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SHA256Message) ProtoMessage() {}

func (x *SHA256Message) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_compilation_server_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SHA256Message.ProtoReflect.Descriptor instead.
func (*SHA256Message) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_compilation_server_proto_rawDescGZIP(), []int{0}
}

func (x *SHA256Message) GetB0_7() uint64 {
	if x != nil {
		return x.B0_7
	}
	return 0
}

func (x *SHA256Message) GetB8_15() uint64 {
	if x != nil {
		return x.B8_15
	}
	return 0
}

func (x *SHA256Message) GetB16_23() uint64 {
	if x != nil {
		return x.B16_23
	}
	return 0
}

func (x *SHA256Message) GetB24_31() uint64 {
	if x != nil {
		return x.B24_31
	}
	return 0
}

type HeaderMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FilePath string `protobuf:"bytes,1,opt,name=FilePath,proto3" json:"FilePath,omitempty"`
	MTime    int64  `protobuf:"varint,2,opt,name=MTime,proto3" json:"MTime,omitempty"`
}

func (x *HeaderMetadata) Reset() {
	*x = HeaderMetadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_v1_compilation_server_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeaderMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeaderMetadata) ProtoMessage() {}

func (x *HeaderMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_compilation_server_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeaderMetadata.ProtoReflect.Descriptor instead.
func (*HeaderMetadata) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_compilation_server_proto_rawDescGZIP(), []int{1}
}

func (x *HeaderMetadata) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *HeaderMetadata) GetMTime() int64 {
	if x != nil {
		return x.MTime
	}
	return 0
}

type StartCompilationSessionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID          *SHA256Message    `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	SourceFilePath  string            `protobuf:"bytes,2,opt,name=SourceFilePath,proto3" json:"SourceFilePath,omitempty"`
	Compiler        string            `protobuf:"bytes,3,opt,name=Compiler,proto3" json:"Compiler,omitempty"`
	CompilerArgs    []string          `protobuf:"bytes,4,rep,name=CompilerArgs,proto3" json:"CompilerArgs,omitempty"`
	RequiredHeaders []*HeaderMetadata `protobuf:"bytes,5,rep,name=RequiredHeaders,proto3" json:"RequiredHeaders,omitempty"`
}

func (x *StartCompilationSessionRequest) Reset() {
	*x = StartCompilationSessionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_v1_compilation_server_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartCompilationSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartCompilationSessionRequest) ProtoMessage() {}

func (x *StartCompilationSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_compilation_server_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartCompilationSessionRequest.ProtoReflect.Descriptor instead.
func (*StartCompilationSessionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_compilation_server_proto_rawDescGZIP(), []int{2}
}

func (x *StartCompilationSessionRequest) GetUserID() *SHA256Message {
	if x != nil {
		return x.UserID
	}
	return nil
}

func (x *StartCompilationSessionRequest) GetSourceFilePath() string {
	if x != nil {
		return x.SourceFilePath
	}
	return ""
}

func (x *StartCompilationSessionRequest) GetCompiler() string {
	if x != nil {
		return x.Compiler
	}
	return ""
}

func (x *StartCompilationSessionRequest) GetCompilerArgs() []string {
	if x != nil {
		return x.CompilerArgs
	}
	return nil
}

func (x *StartCompilationSessionRequest) GetRequiredHeaders() []*HeaderMetadata {
	if x != nil {
		return x.RequiredHeaders
	}
	return nil
}

type StartCompilationSessionReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionID             uint64  `protobuf:"varint,1,opt,name=SessionID,proto3" json:"SessionID,omitempty"`
	MissedHeadersSHA256   []int32 `protobuf:"varint,2,rep,packed,name=MissedHeadersSHA256,proto3" json:"MissedHeadersSHA256,omitempty"`
	MissedHeadersFullCopy []int32 `protobuf:"varint,3,rep,packed,name=MissedHeadersFullCopy,proto3" json:"MissedHeadersFullCopy,omitempty"`
}

func (x *StartCompilationSessionReply) Reset() {
	*x = StartCompilationSessionReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_v1_compilation_server_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartCompilationSessionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartCompilationSessionReply) ProtoMessage() {}

func (x *StartCompilationSessionReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_compilation_server_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartCompilationSessionReply.ProtoReflect.Descriptor instead.
func (*StartCompilationSessionReply) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_compilation_server_proto_rawDescGZIP(), []int{3}
}

func (x *StartCompilationSessionReply) GetSessionID() uint64 {
	if x != nil {
		return x.SessionID
	}
	return 0
}

func (x *StartCompilationSessionReply) GetMissedHeadersSHA256() []int32 {
	if x != nil {
		return x.MissedHeadersSHA256
	}
	return nil
}

func (x *StartCompilationSessionReply) GetMissedHeadersFullCopy() []int32 {
	if x != nil {
		return x.MissedHeadersFullCopy
	}
	return nil
}

type SendHeaderSHA256Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionID    uint64         `protobuf:"varint,1,opt,name=SessionID,proto3" json:"SessionID,omitempty"`
	HeaderIndex  int32          `protobuf:"varint,2,opt,name=HeaderIndex,proto3" json:"HeaderIndex,omitempty"`
	HeaderSHA256 *SHA256Message `protobuf:"bytes,3,opt,name=HeaderSHA256,proto3" json:"HeaderSHA256,omitempty"`
}

func (x *SendHeaderSHA256Request) Reset() {
	*x = SendHeaderSHA256Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_v1_compilation_server_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendHeaderSHA256Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendHeaderSHA256Request) ProtoMessage() {}

func (x *SendHeaderSHA256Request) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_compilation_server_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendHeaderSHA256Request.ProtoReflect.Descriptor instead.
func (*SendHeaderSHA256Request) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_compilation_server_proto_rawDescGZIP(), []int{4}
}

func (x *SendHeaderSHA256Request) GetSessionID() uint64 {
	if x != nil {
		return x.SessionID
	}
	return 0
}

func (x *SendHeaderSHA256Request) GetHeaderIndex() int32 {
	if x != nil {
		return x.HeaderIndex
	}
	return 0
}

func (x *SendHeaderSHA256Request) GetHeaderSHA256() *SHA256Message {
	if x != nil {
		return x.HeaderSHA256
	}
	return nil
}

type SendHeaderSHA256Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FullCopyRequired bool `protobuf:"varint,1,opt,name=FullCopyRequired,proto3" json:"FullCopyRequired,omitempty"`
}

func (x *SendHeaderSHA256Reply) Reset() {
	*x = SendHeaderSHA256Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_v1_compilation_server_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendHeaderSHA256Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendHeaderSHA256Reply) ProtoMessage() {}

func (x *SendHeaderSHA256Reply) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_compilation_server_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendHeaderSHA256Reply.ProtoReflect.Descriptor instead.
func (*SendHeaderSHA256Reply) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_compilation_server_proto_rawDescGZIP(), []int{5}
}

func (x *SendHeaderSHA256Reply) GetFullCopyRequired() bool {
	if x != nil {
		return x.FullCopyRequired
	}
	return false
}

type SendHeaderRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Chunk:
	//	*SendHeaderRequest_Metadata
	//	*SendHeaderRequest_HeaderBodyChunk
	Chunk isSendHeaderRequest_Chunk `protobuf_oneof:"Chunk"`
}

func (x *SendHeaderRequest) Reset() {
	*x = SendHeaderRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_v1_compilation_server_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendHeaderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendHeaderRequest) ProtoMessage() {}

func (x *SendHeaderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_compilation_server_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendHeaderRequest.ProtoReflect.Descriptor instead.
func (*SendHeaderRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_compilation_server_proto_rawDescGZIP(), []int{6}
}

func (m *SendHeaderRequest) GetChunk() isSendHeaderRequest_Chunk {
	if m != nil {
		return m.Chunk
	}
	return nil
}

func (x *SendHeaderRequest) GetMetadata() *SendHeaderRequest_HeaderMetadata {
	if x, ok := x.GetChunk().(*SendHeaderRequest_Metadata); ok {
		return x.Metadata
	}
	return nil
}

func (x *SendHeaderRequest) GetHeaderBodyChunk() []byte {
	if x, ok := x.GetChunk().(*SendHeaderRequest_HeaderBodyChunk); ok {
		return x.HeaderBodyChunk
	}
	return nil
}

type isSendHeaderRequest_Chunk interface {
	isSendHeaderRequest_Chunk()
}

type SendHeaderRequest_Metadata struct {
	Metadata *SendHeaderRequest_HeaderMetadata `protobuf:"bytes,1,opt,name=Metadata,proto3,oneof"`
}

type SendHeaderRequest_HeaderBodyChunk struct {
	HeaderBodyChunk []byte `protobuf:"bytes,2,opt,name=HeaderBodyChunk,proto3,oneof"`
}

func (*SendHeaderRequest_Metadata) isSendHeaderRequest_Chunk() {}

func (*SendHeaderRequest_HeaderBodyChunk) isSendHeaderRequest_Chunk() {}

type SendHeaderReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SendHeaderReply) Reset() {
	*x = SendHeaderReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_v1_compilation_server_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendHeaderReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendHeaderReply) ProtoMessage() {}

func (x *SendHeaderReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_compilation_server_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendHeaderReply.ProtoReflect.Descriptor instead.
func (*SendHeaderReply) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_compilation_server_proto_rawDescGZIP(), []int{7}
}

type CompileSourceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionID              uint64 `protobuf:"varint,1,opt,name=SessionID,proto3" json:"SessionID,omitempty"`
	SourceBody             []byte `protobuf:"bytes,2,opt,name=SourceBody,proto3" json:"SourceBody,omitempty"`
	CloseSessionAfterBuild bool   `protobuf:"varint,3,opt,name=CloseSessionAfterBuild,proto3" json:"CloseSessionAfterBuild,omitempty"`
}

func (x *CompileSourceRequest) Reset() {
	*x = CompileSourceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_v1_compilation_server_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompileSourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompileSourceRequest) ProtoMessage() {}

func (x *CompileSourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_compilation_server_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompileSourceRequest.ProtoReflect.Descriptor instead.
func (*CompileSourceRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_compilation_server_proto_rawDescGZIP(), []int{8}
}

func (x *CompileSourceRequest) GetSessionID() uint64 {
	if x != nil {
		return x.SessionID
	}
	return 0
}

func (x *CompileSourceRequest) GetSourceBody() []byte {
	if x != nil {
		return x.SourceBody
	}
	return nil
}

func (x *CompileSourceRequest) GetCloseSessionAfterBuild() bool {
	if x != nil {
		return x.CloseSessionAfterBuild
	}
	return false
}

type CompileSourceReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CompilerRetCode int32  `protobuf:"varint,1,opt,name=CompilerRetCode,proto3" json:"CompilerRetCode,omitempty"`
	CompiledSource  []byte `protobuf:"bytes,2,opt,name=CompiledSource,proto3" json:"CompiledSource,omitempty"`
	CompilerStdout  []byte `protobuf:"bytes,3,opt,name=CompilerStdout,proto3" json:"CompilerStdout,omitempty"`
	CompilerStderr  []byte `protobuf:"bytes,4,opt,name=CompilerStderr,proto3" json:"CompilerStderr,omitempty"`
}

func (x *CompileSourceReply) Reset() {
	*x = CompileSourceReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_v1_compilation_server_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompileSourceReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompileSourceReply) ProtoMessage() {}

func (x *CompileSourceReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_compilation_server_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompileSourceReply.ProtoReflect.Descriptor instead.
func (*CompileSourceReply) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_compilation_server_proto_rawDescGZIP(), []int{9}
}

func (x *CompileSourceReply) GetCompilerRetCode() int32 {
	if x != nil {
		return x.CompilerRetCode
	}
	return 0
}

func (x *CompileSourceReply) GetCompiledSource() []byte {
	if x != nil {
		return x.CompiledSource
	}
	return nil
}

func (x *CompileSourceReply) GetCompilerStdout() []byte {
	if x != nil {
		return x.CompilerStdout
	}
	return nil
}

func (x *CompileSourceReply) GetCompilerStderr() []byte {
	if x != nil {
		return x.CompilerStderr
	}
	return nil
}

type CloseSessionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionID uint64 `protobuf:"varint,1,opt,name=SessionID,proto3" json:"SessionID,omitempty"`
}

func (x *CloseSessionRequest) Reset() {
	*x = CloseSessionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_v1_compilation_server_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CloseSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseSessionRequest) ProtoMessage() {}

func (x *CloseSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_compilation_server_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseSessionRequest.ProtoReflect.Descriptor instead.
func (*CloseSessionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_compilation_server_proto_rawDescGZIP(), []int{10}
}

func (x *CloseSessionRequest) GetSessionID() uint64 {
	if x != nil {
		return x.SessionID
	}
	return 0
}

type CloseSessionReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CloseSessionReply) Reset() {
	*x = CloseSessionReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_v1_compilation_server_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CloseSessionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseSessionReply) ProtoMessage() {}

func (x *CloseSessionReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_compilation_server_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseSessionReply.ProtoReflect.Descriptor instead.
func (*CloseSessionReply) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_compilation_server_proto_rawDescGZIP(), []int{11}
}

type StatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_v1_compilation_server_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_compilation_server_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_compilation_server_proto_rawDescGZIP(), []int{12}
}

type StatusReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerVersion string   `protobuf:"bytes,1,opt,name=ServerVersion,proto3" json:"ServerVersion,omitempty"`
	ServerArgs    []string `protobuf:"bytes,2,rep,name=ServerArgs,proto3" json:"ServerArgs,omitempty"`
	ServerStats   []byte   `protobuf:"bytes,3,opt,name=ServerStats,proto3" json:"ServerStats,omitempty"`
}

func (x *StatusReply) Reset() {
	*x = StatusReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_v1_compilation_server_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatusReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusReply) ProtoMessage() {}

func (x *StatusReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_compilation_server_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusReply.ProtoReflect.Descriptor instead.
func (*StatusReply) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_compilation_server_proto_rawDescGZIP(), []int{13}
}

func (x *StatusReply) GetServerVersion() string {
	if x != nil {
		return x.ServerVersion
	}
	return ""
}

func (x *StatusReply) GetServerArgs() []string {
	if x != nil {
		return x.ServerArgs
	}
	return nil
}

func (x *StatusReply) GetServerStats() []byte {
	if x != nil {
		return x.ServerStats
	}
	return nil
}

type SendHeaderRequest_HeaderMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionID   uint64 `protobuf:"varint,1,opt,name=SessionID,proto3" json:"SessionID,omitempty"`
	HeaderIndex int32  `protobuf:"varint,2,opt,name=HeaderIndex,proto3" json:"HeaderIndex,omitempty"`
}

func (x *SendHeaderRequest_HeaderMetadata) Reset() {
	*x = SendHeaderRequest_HeaderMetadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_v1_compilation_server_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendHeaderRequest_HeaderMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendHeaderRequest_HeaderMetadata) ProtoMessage() {}

func (x *SendHeaderRequest_HeaderMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_compilation_server_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendHeaderRequest_HeaderMetadata.ProtoReflect.Descriptor instead.
func (*SendHeaderRequest_HeaderMetadata) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_compilation_server_proto_rawDescGZIP(), []int{6, 0}
}

func (x *SendHeaderRequest_HeaderMetadata) GetSessionID() uint64 {
	if x != nil {
		return x.SessionID
	}
	return 0
}

func (x *SendHeaderRequest_HeaderMetadata) GetHeaderIndex() int32 {
	if x != nil {
		return x.HeaderIndex
	}
	return 0
}

var File_api_proto_v1_compilation_server_proto protoreflect.FileDescriptor

var file_api_proto_v1_compilation_server_proto_rawDesc = []byte{
	0x0a, 0x25, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x31, 0x2f, 0x63,
	0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x70, 0x6f, 0x70, 0x63, 0x6f, 0x72, 0x6e,
	0x22, 0x65, 0x0a, 0x0d, 0x53, 0x48, 0x41, 0x32, 0x35, 0x36, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x11, 0x0a, 0x04, 0x42, 0x30, 0x5f, 0x37, 0x18, 0x01, 0x20, 0x01, 0x28, 0x06, 0x52,
	0x03, 0x42, 0x30, 0x37, 0x12, 0x13, 0x0a, 0x05, 0x42, 0x38, 0x5f, 0x31, 0x35, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x06, 0x52, 0x04, 0x42, 0x38, 0x31, 0x35, 0x12, 0x15, 0x0a, 0x06, 0x42, 0x31, 0x36,
	0x5f, 0x32, 0x33, 0x18, 0x03, 0x20, 0x01, 0x28, 0x06, 0x52, 0x05, 0x42, 0x31, 0x36, 0x32, 0x33,
	0x12, 0x15, 0x0a, 0x06, 0x42, 0x32, 0x34, 0x5f, 0x33, 0x31, 0x18, 0x04, 0x20, 0x01, 0x28, 0x06,
	0x52, 0x05, 0x42, 0x32, 0x34, 0x33, 0x31, 0x22, 0x42, 0x0a, 0x0e, 0x48, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x1a, 0x0a, 0x08, 0x46, 0x69, 0x6c,
	0x65, 0x50, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x46, 0x69, 0x6c,
	0x65, 0x50, 0x61, 0x74, 0x68, 0x12, 0x14, 0x0a, 0x05, 0x4d, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x4d, 0x54, 0x69, 0x6d, 0x65, 0x22, 0xfb, 0x01, 0x0a, 0x1e,
	0x53, 0x74, 0x61, 0x72, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2e,
	0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16,
	0x2e, 0x70, 0x6f, 0x70, 0x63, 0x6f, 0x72, 0x6e, 0x2e, 0x53, 0x48, 0x41, 0x32, 0x35, 0x36, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x26,
	0x0a, 0x0e, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x50, 0x61, 0x74, 0x68,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x46, 0x69,
	0x6c, 0x65, 0x50, 0x61, 0x74, 0x68, 0x12, 0x1a, 0x0a, 0x08, 0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c,
	0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c,
	0x65, 0x72, 0x12, 0x22, 0x0a, 0x0c, 0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x65, 0x72, 0x41, 0x72,
	0x67, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0c, 0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c,
	0x65, 0x72, 0x41, 0x72, 0x67, 0x73, 0x12, 0x41, 0x0a, 0x0f, 0x52, 0x65, 0x71, 0x75, 0x69, 0x72,
	0x65, 0x64, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x17, 0x2e, 0x70, 0x6f, 0x70, 0x63, 0x6f, 0x72, 0x6e, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x0f, 0x52, 0x65, 0x71, 0x75, 0x69, 0x72,
	0x65, 0x64, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x22, 0xa4, 0x01, 0x0a, 0x1c, 0x53, 0x74,
	0x61, 0x72, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x53,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x12, 0x30, 0x0a, 0x13, 0x4d, 0x69, 0x73, 0x73,
	0x65, 0x64, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x53, 0x48, 0x41, 0x32, 0x35, 0x36, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x05, 0x52, 0x13, 0x4d, 0x69, 0x73, 0x73, 0x65, 0x64, 0x48, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x73, 0x53, 0x48, 0x41, 0x32, 0x35, 0x36, 0x12, 0x34, 0x0a, 0x15, 0x4d, 0x69,
	0x73, 0x73, 0x65, 0x64, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x46, 0x75, 0x6c, 0x6c, 0x43,
	0x6f, 0x70, 0x79, 0x18, 0x03, 0x20, 0x03, 0x28, 0x05, 0x52, 0x15, 0x4d, 0x69, 0x73, 0x73, 0x65,
	0x64, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x46, 0x75, 0x6c, 0x6c, 0x43, 0x6f, 0x70, 0x79,
	0x22, 0x95, 0x01, 0x0a, 0x17, 0x53, 0x65, 0x6e, 0x64, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x53,
	0x48, 0x41, 0x32, 0x35, 0x36, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09,
	0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x09, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x12, 0x20, 0x0a, 0x0b, 0x48, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0b, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x3a, 0x0a, 0x0c,
	0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x53, 0x48, 0x41, 0x32, 0x35, 0x36, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x6f, 0x70, 0x63, 0x6f, 0x72, 0x6e, 0x2e, 0x53, 0x48, 0x41,
	0x32, 0x35, 0x36, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x0c, 0x48, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x53, 0x48, 0x41, 0x32, 0x35, 0x36, 0x22, 0x43, 0x0a, 0x15, 0x53, 0x65, 0x6e, 0x64,
	0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x53, 0x48, 0x41, 0x32, 0x35, 0x36, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x2a, 0x0a, 0x10, 0x46, 0x75, 0x6c, 0x6c, 0x43, 0x6f, 0x70, 0x79, 0x52, 0x65, 0x71,
	0x75, 0x69, 0x72, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x10, 0x46, 0x75, 0x6c,
	0x6c, 0x43, 0x6f, 0x70, 0x79, 0x52, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x22, 0xe3, 0x01,
	0x0a, 0x11, 0x53, 0x65, 0x6e, 0x64, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x47, 0x0a, 0x08, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x70, 0x6f, 0x70, 0x63, 0x6f, 0x72, 0x6e, 0x2e,
	0x53, 0x65, 0x6e, 0x64, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61,
	0x48, 0x00, 0x52, 0x08, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x2a, 0x0a, 0x0f,
	0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x42, 0x6f, 0x64, 0x79, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x0f, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x42,
	0x6f, 0x64, 0x79, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x1a, 0x50, 0x0a, 0x0e, 0x48, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x53,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x12, 0x20, 0x0a, 0x0b, 0x48, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x48,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x42, 0x07, 0x0a, 0x05, 0x43, 0x68,
	0x75, 0x6e, 0x6b, 0x22, 0x11, 0x0a, 0x0f, 0x53, 0x65, 0x6e, 0x64, 0x48, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x8c, 0x01, 0x0a, 0x14, 0x43, 0x6f, 0x6d, 0x70, 0x69,
	0x6c, 0x65, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1c, 0x0a, 0x09, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x09, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x12, 0x1e, 0x0a,
	0x0a, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x42, 0x6f, 0x64, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x0a, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x36, 0x0a,
	0x16, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x41, 0x66, 0x74,
	0x65, 0x72, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x16, 0x43,
	0x6c, 0x6f, 0x73, 0x65, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x41, 0x66, 0x74, 0x65, 0x72,
	0x42, 0x75, 0x69, 0x6c, 0x64, 0x22, 0xb6, 0x01, 0x0a, 0x12, 0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c,
	0x65, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x28, 0x0a, 0x0f,
	0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x65, 0x72, 0x52, 0x65, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0f, 0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x65, 0x72, 0x52,
	0x65, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c,
	0x65, 0x64, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0e,
	0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x65, 0x64, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x26,
	0x0a, 0x0e, 0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x65, 0x72, 0x53, 0x74, 0x64, 0x6f, 0x75, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0e, 0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x65, 0x72,
	0x53, 0x74, 0x64, 0x6f, 0x75, 0x74, 0x12, 0x26, 0x0a, 0x0e, 0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c,
	0x65, 0x72, 0x53, 0x74, 0x64, 0x65, 0x72, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0e,
	0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x65, 0x72, 0x53, 0x74, 0x64, 0x65, 0x72, 0x72, 0x22, 0x33,
	0x0a, 0x13, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x49, 0x44, 0x22, 0x13, 0x0a, 0x11, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x53, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x0f, 0x0a, 0x0d, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x75, 0x0a, 0x0b, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x24, 0x0a, 0x0d, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0d, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1e,
	0x0a, 0x0a, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x41, 0x72, 0x67, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x0a, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x41, 0x72, 0x67, 0x73, 0x12, 0x20,
	0x0a, 0x0b, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x73, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x0b, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x73,
	0x32, 0xf6, 0x03, 0x0a, 0x12, 0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x6b, 0x0a, 0x17, 0x53, 0x74, 0x61, 0x72, 0x74,
	0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x12, 0x27, 0x2e, 0x70, 0x6f, 0x70, 0x63, 0x6f, 0x72, 0x6e, 0x2e, 0x53, 0x74, 0x61,
	0x72, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x70, 0x6f,
	0x70, 0x63, 0x6f, 0x72, 0x6e, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x69,
	0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x22, 0x00, 0x12, 0x56, 0x0a, 0x10, 0x53, 0x65, 0x6e, 0x64, 0x48, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x53, 0x48, 0x41, 0x32, 0x35, 0x36, 0x12, 0x20, 0x2e, 0x70, 0x6f, 0x70, 0x63, 0x6f,
	0x72, 0x6e, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x53, 0x48, 0x41,
	0x32, 0x35, 0x36, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x70, 0x6f, 0x70,
	0x63, 0x6f, 0x72, 0x6e, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x53,
	0x48, 0x41, 0x32, 0x35, 0x36, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x46, 0x0a, 0x0a,
	0x53, 0x65, 0x6e, 0x64, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x1a, 0x2e, 0x70, 0x6f, 0x70,
	0x63, 0x6f, 0x72, 0x6e, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x70, 0x6f, 0x70, 0x63, 0x6f, 0x72, 0x6e,
	0x2e, 0x53, 0x65, 0x6e, 0x64, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x22, 0x00, 0x28, 0x01, 0x12, 0x4d, 0x0a, 0x0d, 0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x65, 0x53,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x1d, 0x2e, 0x70, 0x6f, 0x70, 0x63, 0x6f, 0x72, 0x6e, 0x2e,
	0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x65, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x70, 0x6f, 0x70, 0x63, 0x6f, 0x72, 0x6e, 0x2e, 0x43,
	0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x65, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x22, 0x00, 0x12, 0x4a, 0x0a, 0x0c, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x53, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x2e, 0x70, 0x6f, 0x70, 0x63, 0x6f, 0x72, 0x6e, 0x2e, 0x43, 0x6c,
	0x6f, 0x73, 0x65, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1a, 0x2e, 0x70, 0x6f, 0x70, 0x63, 0x6f, 0x72, 0x6e, 0x2e, 0x43, 0x6c, 0x6f, 0x73,
	0x65, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12,
	0x38, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x16, 0x2e, 0x70, 0x6f, 0x70, 0x63,
	0x6f, 0x72, 0x6e, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x14, 0x2e, 0x70, 0x6f, 0x70, 0x63, 0x6f, 0x72, 0x6e, 0x2e, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x30, 0x5a, 0x2e, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x41, 0x6c, 0x65, 0x78, 0x4b, 0x30, 0x2f, 0x70,
	0x6f, 0x70, 0x63, 0x6f, 0x72, 0x6e, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x70, 0x6f, 0x70, 0x63, 0x6f, 0x72, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_api_proto_v1_compilation_server_proto_rawDescOnce sync.Once
	file_api_proto_v1_compilation_server_proto_rawDescData = file_api_proto_v1_compilation_server_proto_rawDesc
)

func file_api_proto_v1_compilation_server_proto_rawDescGZIP() []byte {
	file_api_proto_v1_compilation_server_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_compilation_server_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_v1_compilation_server_proto_rawDescData)
	})
	return file_api_proto_v1_compilation_server_proto_rawDescData
}

var file_api_proto_v1_compilation_server_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_api_proto_v1_compilation_server_proto_goTypes = []interface{}{
	(*SHA256Message)(nil),                    // 0: popcorn.SHA256Message
	(*HeaderMetadata)(nil),                   // 1: popcorn.HeaderMetadata
	(*StartCompilationSessionRequest)(nil),   // 2: popcorn.StartCompilationSessionRequest
	(*StartCompilationSessionReply)(nil),     // 3: popcorn.StartCompilationSessionReply
	(*SendHeaderSHA256Request)(nil),          // 4: popcorn.SendHeaderSHA256Request
	(*SendHeaderSHA256Reply)(nil),            // 5: popcorn.SendHeaderSHA256Reply
	(*SendHeaderRequest)(nil),                // 6: popcorn.SendHeaderRequest
	(*SendHeaderReply)(nil),                  // 7: popcorn.SendHeaderReply
	(*CompileSourceRequest)(nil),             // 8: popcorn.CompileSourceRequest
	(*CompileSourceReply)(nil),               // 9: popcorn.CompileSourceReply
	(*CloseSessionRequest)(nil),              // 10: popcorn.CloseSessionRequest
	(*CloseSessionReply)(nil),                // 11: popcorn.CloseSessionReply
	(*StatusRequest)(nil),                    // 12: popcorn.StatusRequest
	(*StatusReply)(nil),                      // 13: popcorn.StatusReply
	(*SendHeaderRequest_HeaderMetadata)(nil), // 14: popcorn.SendHeaderRequest.HeaderMetadata
}
var file_api_proto_v1_compilation_server_proto_depIdxs = []int32{
	0,  // 0: popcorn.StartCompilationSessionRequest.UserID:type_name -> popcorn.SHA256Message
	1,  // 1: popcorn.StartCompilationSessionRequest.RequiredHeaders:type_name -> popcorn.HeaderMetadata
	0,  // 2: popcorn.SendHeaderSHA256Request.HeaderSHA256:type_name -> popcorn.SHA256Message
	14, // 3: popcorn.SendHeaderRequest.Metadata:type_name -> popcorn.SendHeaderRequest.HeaderMetadata
	2,  // 4: popcorn.CompilationService.StartCompilationSession:input_type -> popcorn.StartCompilationSessionRequest
	4,  // 5: popcorn.CompilationService.SendHeaderSHA256:input_type -> popcorn.SendHeaderSHA256Request
	6,  // 6: popcorn.CompilationService.SendHeader:input_type -> popcorn.SendHeaderRequest
	8,  // 7: popcorn.CompilationService.CompileSource:input_type -> popcorn.CompileSourceRequest
	10, // 8: popcorn.CompilationService.CloseSession:input_type -> popcorn.CloseSessionRequest
	12, // 9: popcorn.CompilationService.Status:input_type -> popcorn.StatusRequest
	3,  // 10: popcorn.CompilationService.StartCompilationSession:output_type -> popcorn.StartCompilationSessionReply
	5,  // 11: popcorn.CompilationService.SendHeaderSHA256:output_type -> popcorn.SendHeaderSHA256Reply
	7,  // 12: popcorn.CompilationService.SendHeader:output_type -> popcorn.SendHeaderReply
	9,  // 13: popcorn.CompilationService.CompileSource:output_type -> popcorn.CompileSourceReply
	11, // 14: popcorn.CompilationService.CloseSession:output_type -> popcorn.CloseSessionReply
	13, // 15: popcorn.CompilationService.Status:output_type -> popcorn.StatusReply
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_api_proto_v1_compilation_server_proto_init() }
func file_api_proto_v1_compilation_server_proto_init() {
	if File_api_proto_v1_compilation_server_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_proto_v1_compilation_server_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SHA256Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_v1_compilation_server_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeaderMetadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_v1_compilation_server_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartCompilationSessionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_v1_compilation_server_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartCompilationSessionReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_v1_compilation_server_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendHeaderSHA256Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_v1_compilation_server_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendHeaderSHA256Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_v1_compilation_server_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendHeaderRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_v1_compilation_server_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendHeaderReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_v1_compilation_server_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompileSourceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_v1_compilation_server_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompileSourceReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_v1_compilation_server_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CloseSessionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_v1_compilation_server_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CloseSessionReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_v1_compilation_server_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_v1_compilation_server_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatusReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_v1_compilation_server_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendHeaderRequest_HeaderMetadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_api_proto_v1_compilation_server_proto_msgTypes[6].OneofWrappers = []interface{}{
		(*SendHeaderRequest_Metadata)(nil),
		(*SendHeaderRequest_HeaderBodyChunk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_v1_compilation_server_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_v1_compilation_server_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_compilation_server_proto_depIdxs,
		MessageInfos:      file_api_proto_v1_compilation_server_proto_msgTypes,
	}.Build()
	File_api_proto_v1_compilation_server_proto = out.File
	file_api_proto_v1_compilation_server_proto_rawDesc = nil
	file_api_proto_v1_compilation_server_proto_goTypes = nil
	file_api_proto_v1_compilation_server_proto_depIdxs = nil
}
